### ISSUE TITLE
Bump ASM opcode version

### ISSUE THREAD

**Issue by nstdio** [bmuschko/gradle-docker-plugin#1011]
If project has an `record` class in it the `com.bmuschko.gradle.docker.internal.MainClassFinder` is unable to find the main class.

### Expected Behavior

Successfully find the main class.

### Current Behavior

Throws an exception:

```
Caused by: java.lang.UnsupportedOperationException: Records requires ASM8
	at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:112)
	at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
	at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at com.bmuschko.gradle.docker.internal.MainClassFinder.createClassDescriptor(MainClassFinder.groovy:163)
	at com.bmuschko.gradle.docker.internal.MainClassFinder.doWithMainClasses(MainClassFinder.groovy:132)
	at com.bmuschko.gradle.docker.internal.MainClassFinder.findSingleMainClass(MainClassFinder.groovy:27)
	at com.bmuschko.gradle.docker.DockerSpringBootApplicationPlugin.findMainClassName(DockerSpringBootApplicationPlugin.groovy:32)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin.getApplicationMainClassName(DockerConventionJvmApplicationPlugin.groovy:205)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin.access$1(DockerConventionJvmApplicationPlugin.groovy)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin$2$7.call(DockerConventionJvmApplicationPlugin.groovy:131)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin$2$7.call(DockerConventionJvmApplicationPlugin.groovy)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
```
### Context

Unable to use `gradle-docker-plugin` if have an `record` classes in the source code.

### Steps to Reproduce (for bugs)

In order to reproduce put a `record` in the project source code and execute `dockerCreateDockerfile` task.

### Your Environment

    plugin-version: 7.0.0
    gradle-version: 6.8.3
    docker-version: 20.10.6
    platform: Ubuntu 18.04.5

**Comment by nstdio** [comment]
Related to #999
