### ISSUE TITLE
Error during callback "java.net.SocketTimeoutException: Read timed out" - Regression in 7.0.0 / 7.1.0+ caused by httpcomponents-core 5.0.2+ - works in 6.7.0

### ISSUE THREAD

**Issue by tkrah** [bmuschko/gradle-docker-plugin#1022]
Running a docker build on a "slow" ci machine does fail with plugin version 7.0.0 while 6.7.0 does work. Running the same build on a faster machine with SSD as I/O storage it succeeds with 7.0.0, so this looks like a timing / timeout problem here - but there is no hint in the release notes how to configure that new read timeout which gets applied.

### Expected Behavior
Build should succeed with 7.0.0 like it was in 6.7.0.

### Current Behavior
This is the stacktrace we get when updating plugin version to 7.0.0:

```
Error during callback
java.net.SocketTimeoutException: Read timed out
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:219)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:3005)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3000)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:716)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:243)
	at com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:314)
	at com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:298)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
```

### Context
Just run a build which takes some time, the build in question does inflate an archive which takes some time and will eventually fail because of that timeout message above.

### Steps to Reproduce (for bugs)
I can't share that Dockerfile.
But you should be able to reproduce that by using a script which just does not output anything on stdout/stderr and just takes some time and it will fail with that read timeout.

### Your Environment
JDK 11, Plugin Version 7.0.0, Jenkins + slow I/O

**Comment by bmuschko** [comment]
Version 7.0.0 of the plugin upgraded the version of Docker Java which might have pulled in a newer version of Apache HttpClient 5. This library might use different default or Docker Java changed the connection timeouts on their end. I won't have the time to check their release notes but feel free to do so on your end.

At this time, the plugin does not expose a way to configure those connection timeout settings. A `Read timed out` sounds to me like a connection could be established but it didn't receive any data in a given time. You may really want to identify the issue with your CI machine. Sounds like your company should invest into better infrastructure for such an important part of your delivery pipeline. I'd assume that even if the machine is slow, it would still receive data. Maybe you have some networking issue going on as well.

**Comment by tkrah** [comment]
Checked the release notes but the upstream plugin did not mention anything like that (https://github.com/docker-java/docker-java/releases) - however there is this commit in the 3.2.9 tag:

https://github.com/docker-java/docker-java/pull/1617

Could you please expose those configuration to your docker plugin so we are able to configure such timeouts - the "new" defaults (although I am not yet sure if httpclient oder docker-java changed something here) - seems to be not sufficient for every usecase - although I am still wondering what the plugin does wait for at that point according to the trace above, I have no glue - do you?

6.7.0 is working fine and all versions before do so too (at least starting from 6.1.4).
Even if you are not using a bleeding edge build server (which I can't change here) - and even if you may have bleeding edge stuff, it may happen that slow network or something else would hit that timeout - so it seems just reasonable that we can configure the underlying factory parameters to tune such stuff, do you agree with that?

**Comment by tkrah** [comment]
I got an easy reproducer for you - take this small Dockerfile where we sleep just for 3 minutes (if you succeed take some more seconds - for me 3 minutes is enough to fail - seems the timeout is 180 seconds - so take some more):

```
FROM ubuntu:18.04
RUN sleep 3m
```

If you try it on your localhost make sure you are using e.g. plugin version 7.1.0 and configure the DOCKER_HOST variable like this:

DOCKER_HOST="tcp://127.0.0.1:3333" gradle buildImage

where you replace the host with your own configured host (to make sure unix socket is not used) and the task runs the above Dockerfile.

This will result in:

```
Step 2/2 : RUN sleep 3m
 ---> Running in fbc59be41e42

Error during callback
java.net.SocketTimeoutException: Read timed out
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:219)
        at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:3005)
        at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3000)
        at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:716)
        at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:243)
        at com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:314)
        at com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:298)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)

```
So this is not only a CI problem but can be reproduced on a local machine using the http backend instead of the unix socket (which does not fail here) - and 3 minutes is imho really a too small default timeout.

This should work like in 6.7.0 where both, unix and http is working for this example.

**Comment by tkrah** [comment]
I did also found the cause - its httpcomponents-core in its 5.0.2 release I found this while diffing the tags from 5.0..5.0.3:

```
+Release 5.0.2
+------------------
+Please also note that as of this release HttpCore will use a 3 minute socket timeout
+by default.

```

**Comment by bmuschko** [comment]
Thanks for looking into this. Seems like the timeout was set to 0 before which probably means "no timeout".

I released a new version of the plugin yesterday with the latest version of the Docker Java library. I am little hesitant to expose timeout properties as it would expose the underlying implementation details. Would you be interested in working on a PR for this?

**Comment by tkrah** [comment]
Yes it was 0 before which meant infinite timeout.

Hm - yes it would expose that detail but without a way to configure those the new defaults are a little bit a pita ;-).
I can try to drive a PR for that - although I am not a groovy geek yet, but I can try.

**Comment by bmuschko** [comment]
Looks like the 3 mins default timeout that has been introduced got reverted with Docker Java v3.2.12: https://github.com/docker-java/docker-java/releases/tag/3.2.12. This will make the proposed change obsolete. I will hold off on  exposing timeout configuration options for the HTTP client for now. Thanks again for the PR.

**Comment by tkrah** [comment]
@bmuschko 

I know because I'll reported it there too and they changed it back for it was unexpected in their patch change release. But they will review it and consider changing it back in the future in the next major release.
So this one is still needed to configure those when this will happen and even now - if you actually want something else than infinite.

I must admit it is a little bit irritating that asking for help about the tests for the PR is not answered for more than 3 months (in the light that you are looking for new maintainers) but closing is done in an instant instead of discussing that change further - because like written, this change is still beneficial to configure the timeouts - per task or globally to adjust them to your needs.

So I'll would still prefer if you would accept that PR if it's ready to be merged.

**Comment by tkrah** [comment]
I totally can understand that - reasonable though. But you could / should have told me and I would have tried to provide such a PR which matches your new idea or just tell me that you want to do it yourself - either way is fine - still your project.

I know the back and forth from my daily work in reviewing stuff and how time consuming that is - but for your long term goal getting new people on board you need to take that road imho to find someone suitable, if you don't want to let this plugin starve and eventually die or being forked.

Totally get it that work and life are first priority, I share that priority - my kids are just more important. No worries, your welcome and I appreciate your answer.
