### ISSUE TITLE
DockerLogsContainer cannot be stopped with StopExecutionException

### ISSUE THREAD

**Issue by Bubesz** [bmuschko/gradle-docker-plugin#1029]
...because `catch (Exception e)` is used. Which obviously catches and "handles" StopExecutionExceptions as well, preventing gradle to receive it.

It seems like it was working back then because I found a suggestion to my original problem [here](https://github.com/bmuschko/gradle-docker-plugin/issues/381#issuecomment-327057284).

[StopExecutionException docs](https://docs.gradle.org/5.6.4/javadoc/org/gradle/api/tasks/StopExecutionException.html) for reference.

This is the part of the source code in DockerLogsContainer which I find problematic.
https://github.com/bmuschko/gradle-docker-plugin/blob/650ff702c6dc5bb1f62a190635183d89c1397718/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.groovy#L161

My original, personal problem was the following:
I'd like to wait for my container to be started and healthy before I start other tasks. Since [DockerWaitHealthyContainer](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/container/extras/DockerWaitHealthyContainer.html) 
is deprecated, throwing this exception seemed like the best option for me. I also appreciate it if you can suggest other approaches.
Anyway, I think that catching the generic exception is a bad idea.

```groovy
task createContainer(type: DockerCreateContainer) {
        // params well set for a new postgres container
}
task startContainer(type: DockerStartContainer) {
	dependsOn createContainer
	targetContainerId createContainer.getContainerId()
}
task waitForStartup(type: DockerLogsContainer) {
	dependsOn startContainer
	targetContainerId createContainer.getContainerId()
	follow = true
	tailAll = true
	onNext { message ->
		def foundMessage = message.toString()
		if (foundMessage.contains("database system is ready to accept connections")) {
			throw new StopExecutionException('Postgres is ready to accept connections, we can continue gradle script exection.')
		}
	}
}
task initDatabase {
	dependsOn waitForStartup
	// other config
}
```

This is the output I got, the counter keeps counting, the task keeps waiting for messages.
```
Failed to handle frame
org.gradle.api.GradleException: Postgres is ready to accept connections, we can continue gradle script exection.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
        at build_3axx9wkd3r27k0hfn4vzhgnjj$_run_closure13$_closure22.doCall(C:\Work\workspace-20-03-toolbox\actions-test\build.gradle:106)
        at jdk.internal.reflect.GeneratedMethodAccessor750.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at com.bmuschko.gradle.docker.tasks.container.DockerLogsContainer$2.onNext(DockerLogsContainer.groovy:160)
        at com.bmuschko.gradle.docker.tasks.container.DockerLogsContainer$2.onNext(DockerLogsContainer.groovy)
        at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onNext(AbstrAsyncDockerCmdExec.java:41)
        at com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:78)
        at com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
        at java.base/java.lang.Thread.run(Thread.java:834)
<==========---> 82% EXECUTING [41s]
> :waitForStartup
```

**Comment by aamielsan** [comment]
Also encountered this problem. Had to create a new task that extends `DockerLogsContainer` and override the `logAndProcessResponse()` to remove the `try-catch` block.

```
open class DockerWaitContainerWithLogsTask : DockerLogsContainer() {
    companion object {
        private const val TIMEOUT_VALUE: Long = 3
        private val TIMEOUT_UNIT: TimeUnit = TimeUnit.MINUTES
    }

    override fun logAndProcessResponse(dockerClient: DockerClient) {
        val logCommand: LogContainerCmd = dockerClient
            .logContainerCmd(containerId.get())
            .apply {
                withFollowStream(true)
                withStdOut(true)
                withStdErr(true)
                withTailAll()
            }

        val nextHandler = object : LogContainerResultCallback() {
            override fun onNext(frame: Frame) {
                nextHandler.execute(frame)
                super.onNext(frame)
            }
        }

        logCommand.exec(nextHandler)?.awaitCompletion(TIMEOUT_VALUE, TIMEOUT_UNIT)
    }
}
```

**Comment by bmuschko** [comment]
There are a couple of options you have:

- Implement your own custom task for this purpose.
- Copy the code of `DockerWaitHealthyContainer` into your project.
- Use [TestContainers](https://www.testcontainers.org/). IMHO that's what I would do for the use case.

**Comment by bmuschko** [comment]
Given the provided options, I am going to close the issue.

**Comment by Bubesz** [comment]
Hi Benjamin,
thanks for your fast reaction! I had a very busy week, I had no time to respond, sorry.

I see there are workarounds and it's good at least we have them but this is a clear sign for me that there **_is_** a problem with the code. I'm a bit surprised you closed this. Could you explain me the reason? (Eg. would it be easier if I provided a PR?)

In other words, I see that my personal, original problem can be solved in other ways but (java.lang.)Exception still should be not caught. (It should be specified what types of exceptions are handled. Or worst case: at least what should not be handled.)

**Comment by bmuschko** [comment]
I closed the ticket as I didn't really have time to work on it. I'd be happy to review your PR. Thanks for that. Please add sufficient test coverage.
