### ISSUE TITLE
Error codes can be longs - occurs when process segfaults during container build

### ISSUE THREAD

**Issue by doctorpangloss** [bmuschko/gradle-docker-plugin#1032]
During a Dockerfile build, it's possible to generate an exception that will break the plugin:

```
Error during callback
com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.JsonMappingException: Numeric value (3221225477) out of range of int (-2147483648 - 2147483647)
 at [Source: (com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.io.EofSensorInputStream); line: 24, column: 34] (through reference chain: com.github.dockerjava.api.model.BuildResponseItem["errorDetail"]->com.github.dockerjava.api.model.ResponseItem$ErrorDetail["code"])
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:280)
	at com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:315)
	at com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:298)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
Caused by: com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (3221225477) out of range of int (-2147483648 - 2147483647)
 at [Source: (com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.io.EofSensorInputStream); line: 24, column: 34]
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:601)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:570)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:889)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:802)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:646)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 8 more
```

This is tricky to reproduce in a plain Dockerfile with the rest of my build context. You would need a file that segfaults. Here's what the error code really is:

```
The command '... private ..."' returned a non-zero code: 3221225477
/c/Program Files/Docker/Docker/resources/bin/docker: line 6: 13734 Segmentation fault      "$binary.exe" "$@"
```

Where the private command is a shell in a Windows container.

**Comment by bmuschko** [comment]
From the stack trace provided, it seems like the issue is coming from the Jackson library (it has been shaded) or Apache HTTPClient library and not from this plugin directly. I don't think we'll be able to do anything about this. Maybe open an issue for the Docker Java library though I suspect they will say the same.

**Comment by doctorpangloss** [comment]
Sounds good just wanted to document it. It's pretty obscure.
