### ISSUE TITLE
xception in thread "docker-java-stream-26041612" java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.httpclient5.UnixDomainSocket

### ISSUE THREAD

**Issue by simonjhy** [bmuschko/gradle-docker-plugin#1035]
plugin not support arm64 platform

we used docker gradle plugin to run liferay portal docker image in mac M1 arm64, but we got below exception 
Exception in thread "docker-java-stream-26041612" java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.httpclient5.UnixDomainSocket
### Expected Behavior

we hope gradle plugin support arm64 
### Current Behavior

xception in thread "docker-java-stream-26041612" java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.httpclient5.UnixDomainSocket
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:116)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:149)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bmuschko** [comment]
This issue is coming from the [Docker Java library](https://github.com/docker-java/docker-java) and it needs to be fixed there. Please open an issue with them. We can integrate a new version of Docker Java after they release a fix.

**Comment by bsideup** [comment]
@bmuschko I am not sure, actually.

1. `UnixDomainSocket` is a class from docker-java 3.2.5 that is very old, newer versions have it consolidated under the transport abstraction
2. `UnixDomainSocket` was using JNA and JNA has to be updated to work on M1 - I would check which version of JNA is used in gradle-docker-plugin 👍

**Comment by allangomessl** [comment]
for me, it worked.
```kotlin
buildscript {
    dependencies {
        classpath("com.github.docker-java:docker-java:<<LATEST VERSION>>")
        classpath("com.github.docker-java:docker-java-transport-httpclient5:<<LATEST VERSION>>")
    }
}
```

today, latest is 3.2.13
