### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by abendt** [bmuschko/gradle-docker-plugin#1046]
### Expected Behavior

Recently bought a new Apple M1 laptop. One of my builds that use the _gradle-docker-plugin_ fails on the new machine. I'd expect my build to work on the new machine without relevant changes.

### Current Behavior

When running the build an exception is thrown (see stacktrace). Also the build does not terminate anymore

```
$ gw clean build --no-build-cache
Type-safe dependency accessors is an incubating feature.
Exception in thread "docker-java-stream--1363257922" java.lang.UnsatisfiedLinkError: /Users/abendt/Library/Caches/JNA/temp/jna9682336681627328014.tmp: dlopen(/Users/abendt/Library/Caches/JNA/temp/jna9682336681627328014.tmp, 0x0001): tried: '/Users/abendt/Library/Caches/JNA/temp/jna9682336681627328014.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna9682336681627328014.tmp' (no such file)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:137)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:175)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:829)

> Task :app:buildDockerImage
Building image using context '/Users/abendt/Zalando/serial-number-onboarding-management/app/build/dockerImage'.
Using images 'serial-number-onboarding-management:latest'.
<=========----> 69% EXECUTING [7m 35s]
> IDLE
> IDLE
> :app:buildDockerImage
```

### Context

Trying to run an existing build on a new Apple M1 macbook

Task definition
```groovy
task buildDockerImage(type: DockerBuildImage) {
    dependsOn(copyDockerFiles)
    inputDir = copyDockerFiles.destinationDir
    images.add("my-image:latest")
    buildArgs = ["COMMIT": "$System.env.COMMIT_ID"]
    cacheFrom = previousImage
}
```

### Steps to Reproduce (for bugs)

Will provide a standalone example later

### Your Environment

Plugin version
```groovy
plugins {
    id 'com.bmuschko.docker-remote-api' version '7.1.0'
}
```

Gradle version
```bash
$ gw --version

------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Azul Systems, Inc. 11.0.13+8-LTS)
OS:           Mac OS X 12.0.1 aarch64
```

**Comment by bmuschko** [comment]
Looking at the stack trace, it seems like this is an issue with the JDK that doesn't support M1 yet. What version of Java do you use?

**Comment by abendt** [comment]
I am using Zulu 11.0.13

**Comment by bmuschko** [comment]
You may want to check if that distribution and version is compatible with M1. There's no much we can do from our end.

**Comment by abendt** [comment]
I tried out 2 more JDK's (Liberica and Java.net) with no success. Same behaviour.

Looking at this related Bug https://github.com/testcontainers/testcontainers-java/issues/3610:

Could it make sense to update JNA to the latest available version 5.10.0? Looks like there is a newer version available:



```
$ gw buildEnvironment
...
\--- com.bmuschko.docker-remote-api:com.bmuschko.docker-remote-api.gradle.plugin:7.1.0
     \--- com.bmuschko:gradle-docker-plugin:7.1.0
       ...
          |    \--- net.java.dev.jna:jna:5.8.0  ***
      ...
```

**Comment by bmuschko** [comment]
I am sure that's a transitive dependency of Docker Java so you will want to ask them about it. We can upgrade as soon as they picked a compatible version with their library.

**Comment by abendt** [comment]
for reference my workaround :

I am now using an Intel JDK with Rosetta. To install follow these steps:

* edit `~/.sdkman/etc/config`
```
sdkman_rosetta2_compatible=true
```
* now when running `sdk list java` there are additional JDKs 
* install a non native one (e.g. AdoptOpen JDK)
* use gradle with the gradle-docker-plugin

**Comment by abendt** [comment]
> I am sure that's a transitive dependency of Docker Java (see stack trace) so you will want to ask them about it. We can upgrade as soon as they picked a compatible version with their library.

tried to build the plugin locally with the upgraded version. however this doesn't seem to fix the issue...

I will use the mentioned workaround for now

**Comment by bmuschko** [comment]
[Docker Java 3.2.8 supposedly supports M1.](https://github.com/testcontainers/testcontainers-java/issues/3610#issuecomment-820267510) We are actually using an [even newer version of Docker Java](https://github.com/bmuschko/gradle-docker-plugin/blob/v7.1.0/build.gradle.kts#L27-L29) with the plugin version 7.1.0.

**Comment by bmuschko** [comment]
Closing the issue as you found a solution for your problem.

**Comment by abendt** [comment]
@bmuschko I did some more investigation:

This is not an issue of the JDK. Apparenttly i had multiple versions of JNA on the classpath:
* _gradle-docker-plugin_ uses 5.8.0 (which is also the only one supporting Apple M1)
* "org.springframework.boot" depends on 5.7.0
* when importing the project to IntelliJ there is also a version 5.6.0 present (not sure where this is coming from)

In consequence a wrong version is used which is not compatible with Apple M1!

To fix this i have added this snippet to my _build.gradle_ file:

```groovy
buildscript {
    configurations.all {
        it.resolutionStrategy.eachDependency {
            if (it.requested.group == "net.java.dev.jna") {
                it.useVersion "5.8.0"
                it.because "Apple M1 Compatibilty"
            }
        }
    }
}
```

i also had to add a similiar snippet to _buildSrc/build.gradle_ as IntelliJ otherwise still would see an too old version:

```groovy
configurations.all {
     it.resolutionStrategy.eachDependency {
         if (it.requested.group == "net.java.dev.jna") {
             it.useVersion "5.8.0"
             it.because "Apple M1 Compatibilty"
       }
     }
 }
```

**Comment by bmuschko** [comment]
Gradle's default dependency selection strategy uses the highest available version for a configuration. I am confused why it would select a lower version than 5.8.0 except if something enforces it.

**Comment by abendt** [comment]
> Gradle's default dependency selection strategy uses the highest available version for a configuration. I am confused why it would select a lower version than 5.8.0 except if something enforces it.

I agree i find this confusing too

without the change to my _build.gradle_ the buildenvironment looks like this:

```bash
$ gw buildEnvironment
Type-safe dependency accessors is an incubating feature.

> Task :app:buildEnvironment

------------------------------------------------------------
Project ':app'
------------------------------------------------------------

classpath
+--- org.unbroken-dome.test-sets:org.unbroken-dome.test-sets.gradle.plugin:4.0.0
|    ...
+--- org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin:1.6.0
|    ...
+--- org.springframework.boot:org.springframework.boot.gradle.plugin:2.5.6
|    \--- org.springframework.boot:spring-boot-gradle-plugin:2.5.6
|         +--- org.springframework.boot:spring-boot-buildpack-platform:2.5.6
|         |    ...
|         |    +--- net.java.dev.jna:jna-platform:5.7.0
|         |    |    \--- net.java.dev.jna:jna:5.7.0 -> 5.8.0
     ...
|    ...
\--- com.bmuschko.docker-remote-api:com.bmuschko.docker-remote-api.gradle.plugin:7.1.0
     ...
          |    \--- net.java.dev.jna:jna:5.8.0
```

You can see that it is using _net.java.dev.jna:jna-platform:5.7.0_ and _net.java.dev.jna:jna:5.8.0_.
Using the first snippet this is consolidated so both dependencies use 5.8.0.

The other version 5.6.0 is coming from buildSrc:

```
$ cd buildSrc
$ gw dependencies --configuration runtimeClasspath

> Task :dependencies

------------------------------------------------------------
Root project 'buildSrc'
------------------------------------------------------------

runtimeClasspath - Runtime classpath of compilation 'main' (target  (jvm)).
+--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0
|    ...
|    +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.0
|    |    ...
|    |    \--- net.java.dev.jna:jna:5.6.0
...

With the second snippet this is also consolidated to v5.8.0

**Comment by bmuschko** [comment]
> You can see that it is using net.java.dev.jna:jna-platform:5.7.0 and net.java.dev.jna:jna:5.8.0.

`net.java.dev.jna:jna:5.7.0 -> 5.8.0` means that it uses 5.8.0 over 5.7.0 and not both.

**Comment by abendt** [comment]
> `net.java.dev.jna:jna:5.7.0 -> 5.8.0` means that it uses 5.8.0 over 5.7.0 and not both.

i was referring to this:

```
 +--- net.java.dev.jna:jna-platform:5.7.0
|         |    |    \--- net.java.dev.jna:jna:5.7.0 -> 5.8.0
```
thought both version should be aligned. However it seems this is not the issue.

I have created a stripped down setup that can be used to reproduce the issue:
https://github.com/abendt/gradle-applem1-jna-bug

the project is generated using `gradlew init`. I have changed the kotlin version to 1.6 and added a custom task that prints out which JNA jar is actually used.

```
$ cd app
$ gw buildEnvironment

> Task :app:buildEnvironment

------------------------------------------------------------
Project ':app'
------------------------------------------------------------

classpath
\--- com.bmuschko.docker-remote-api:com.bmuschko.docker-remote-api.gradle.plugin:7.1.0
     \--- com.bmuschko:gradle-docker-plugin:7.1.0
          +--- com.github.docker-java:docker-java-core:3.2.10
          |    +--- com.github.docker-java:docker-java-api:3.2.10
          |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.3
          |    |    \--- org.slf4j:slf4j-api:1.7.30
          |    +--- com.github.docker-java:docker-java-transport:3.2.10
          |    +--- org.slf4j:slf4j-api:1.7.30
          |    +--- commons-io:commons-io:2.6
          |    +--- org.apache.commons:commons-compress:1.20
          |    +--- commons-lang:commons-lang:2.6
          |    +--- com.fasterxml.jackson.core:jackson-databind:2.10.3
          |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.3
          |    |    \--- com.fasterxml.jackson.core:jackson-core:2.10.3
          |    +--- com.google.guava:guava:19.0
          |    \--- org.bouncycastle:bcpkix-jdk15on:1.64
          |         \--- org.bouncycastle:bcprov-jdk15on:1.64
          +--- com.github.docker-java:docker-java-api:3.2.10 (*)
          +--- com.github.docker-java:docker-java-transport-httpclient5:3.2.10
          |    +--- com.github.docker-java:docker-java-transport:3.2.10
          |    +--- org.apache.httpcomponents.client5:httpclient5:5.0.3
          |    |    +--- org.apache.httpcomponents.core5:httpcore5:5.0.2
          |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
          |    |    \--- commons-codec:commons-codec:1.13
          |    \--- net.java.dev.jna:jna:5.8.0
          +--- javax.activation:activation:1.1.1
          \--- org.ow2.asm:asm:9.1
$ gw locateJna

> Task :app:locateJna
Class class com.sun.jna.Native was loaded from (file:/Users/abendt/.gradle/caches/jars-9/b8ab939d466c574d43d516184157c1a4/jna-5.6.0.jar <no signer certificates>)
```

You can see that it using the 5.6.0 jar although _buildEnvironment_ lists another jar ...

**Comment by vhagedorn** [comment]
Still having issues with this in 2024 on M1 Max running Sonoma 14.2.1.


I have tried running it with various installed JDK's via `./gradlew -Dorg.gradle.java.home`, and they all seem to fail with the same error:
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /Users/vadim/Library/Caches/JNA/temp/jna13654831988045201640.tmp: dlopen(/Users/vadim/Library/Caches/JNA/temp/jna13654831988045201640.tmp, 0x0001): tried: '/Users/vadim/Library/Caches/JNA/temp/jna13654831988045201640.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/vadim/Library/Caches/JNA/temp/jna13654831988045201640.tmp' (no such file), '/Users/vadim/Library/Caches/JNA/temp/jna13654831988045201640.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')) [in thread "Execution worker"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at com.github.dockerjava.httpclient5.UnixDomainSocket.<clinit>(UnixDomainSocket.java:80)
        ... 148 more
```

The same exact error occurs with both `temurin-20.0.2` and `corretto-17.0.8.1`, as well as the default `openjdk version "20.0.2" 2023-07-18`. gradlew version output:
```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          20.0.2 (Oracle Corporation 20.0.2+9-78)
OS:           Mac OS X 14.2.1 aarch64
```

This is a fresh project with one class and a barebones build.gradle (relevant portion shown):
```gradle
task stopContainer(type: DockerStopContainer) {
    targetContainerId("$ourContainerName")
    onError { exception -> handleError(exception) }
}

task removeContainer(type: DockerRemoveContainer) {
    dependsOn stopContainer
    targetContainerId("$ourContainerName")
    onError { exception -> handleError(exception) }
}

task createContainer(type: DockerCreateContainer) {
    // the goal here is to simply create and run a container as a gradle task, the project itself is not deployed within docker
    dependsOn removeContainer
    targetImageId "$ourContainerName"
    containerName = "$ourContainerName"
    hostConfig.portBindings = ['8000:8000']
}

task startContainer(type: DockerStartContainer) {
    dependsOn createContainer
    targetContainerId("$ourContainerName")
}
```

I've read through the other issues and they all claim the culprit is Docker's Java API, or an unsupported JDK, but 3 years later I would assume these have been resolved, especially considering I tested on multiple JDK's.

Any feedback or guidance would be appreciated; it would be really nice to see this work.

Thanks,
~Vadim

**Comment by bmuschko** [comment]
@vhagedorn Please create a GitHub repository with the code. Make sure that you add a GitHub workflow that reproduces the issue. I can have a look if we have something that shows the issue independent of your developer machine.
