### ISSUE TITLE
Still Apple M1 problems with 7.3.0

### ISSUE THREAD

**Issue by mfriess2** [bmuschko/gradle-docker-plugin#1070]
Hello,

with your newest plugin 7.3.0 and Apple M1 and OpenJDK 11.0.15 (M1 version), I unfortunately still get an error when trying to build images.

### Expected Behavior

`./gradle image` works

### Current Behavior

`./gradle :docker:image` with plugin 7.3.0:
```
> Task :docker:baseImage
Building image using context '/Users/.../docker/build'.
Using Dockerfile '/Users/.../docker/build/Dockerfile'
Using images 'demo:1.1.0-a07f741-SNAPSHOT-base'.

Exception in thread "docker-java-stream--473973909" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
        at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

FYI: `./gradle :docker:image` with plugin 7.2.0 seems to fail at some different error:
```
> Task :docker:baseImage FAILED
Building image using context '/Users/.../docker/build'.
Using Dockerfile '/Users/.../docker/build/Dockerfile'

Execution failed for task ':docker:baseImage'.
> group id '1912341234' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit
```

So maybe something broke from 7.2.0 to 7.3.0?

### Steps to Reproduce (for bugs)

Apple M1 Mac
brew install openjdk@11
./gradlew image

### Your Environment

Output of `gradle -version`:
```
Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Homebrew 11.0.15+0)
OS:           Mac OS X 12.3.1 aarch64
```

gradlew :docker:buildEnvironment:
```
classpath
\--- com.bmuschko.docker-remote-api:com.bmuschko.docker-remote-api.gradle.plugin:7.3.0
     \--- com.bmuschko:gradle-docker-plugin:7.3.0
          +--- com.github.docker-java:docker-java-core:3.2.13
          |    +--- com.github.docker-java:docker-java-api:3.2.13
          |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.3
          |    |    \--- org.slf4j:slf4j-api:1.7.30
          |    +--- com.github.docker-java:docker-java-transport:3.2.13
          |    +--- org.slf4j:slf4j-api:1.7.30
          |    +--- commons-io:commons-io:2.6
          |    +--- org.apache.commons:commons-compress:1.21
          |    +--- org.apache.commons:commons-lang3:3.12.0
          |    +--- com.fasterxml.jackson.core:jackson-databind:2.10.3
          |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.3
          |    |    \--- com.fasterxml.jackson.core:jackson-core:2.10.3
          |    +--- com.google.guava:guava:19.0
          |    \--- org.bouncycastle:bcpkix-jdk15on:1.64
          |         \--- org.bouncycastle:bcprov-jdk15on:1.64
          +--- com.github.docker-java:docker-java-api:3.2.13 (*)
          +--- com.github.docker-java:docker-java-transport-httpclient5:3.2.13
          |    +--- com.github.docker-java:docker-java-transport:3.2.13
          |    +--- org.apache.httpcomponents.client5:httpclient5:5.0.3
          |    |    +--- org.apache.httpcomponents.core5:httpcore5:5.0.2
          |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
          |    |    \--- commons-codec:commons-codec:1.13
          |    \--- net.java.dev.jna:jna:5.8.0
          +--- javax.activation:activation:1.1.1
          \--- org.ow2.asm:asm:9.1

(*) - dependencies omitted (listed previously)
```

**Comment by bmuschko** [comment]
This is an issue with Docker Java. Please open an issue on their GitHub repository. We can incorporate changes as soon as they release a new version.

**Comment by Sineaggi** [comment]
As of java 16, java has a new unix domain socket api. Have you tried running on gradle 16+?

**Comment by mfriess2** [comment]
No, I have not tried Gradle 16, sorry.
It will be no solution for me because my project must use Java 11.

**Comment by kastork** [comment]
> As of java 16, java has a new unix domain socket api. Have you tried running on gradle 16+?

Using Amazon Corretto 17, this error still presents.

I'm using colima (https://github.com/abiosoft/colima) for the local docker implementation, since Docker for Desktop has gone commercial.

**Comment by Sineaggi** [comment]
Hm, what does the Gradle's stacktrace look like @kastork? At least on my machine (intel, not m1) I see java 17 hitting the `java.net.UnixDomainSocketAddress` codepath and succeeding.

**Comment by Sineaggi** [comment]
@mfriess2 I'm not entirely sure what you mean by `my project must use Java 11`. Gradle itself supports running on different versions of java vs the java used to compile your code via [toolchains](https://docs.gradle.org/current/userguide/toolchains.html), and java itself supports cross-compilation via the [--release](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:release) flag.

**Comment by kastork** [comment]
@Sineaggi  Here's my stack trace...


```
 ./gradlew buildNativeLambda
Exception in thread "docker-java-stream--1579929629" java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.httpclient5.UnixDomainSocket
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:149)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

Environment:

```
./gradlew --version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3 (Amazon.com Inc. 17.0.3+6-LTS)
OS:           Mac OS X 12.4 aarch64

```

**Comment by kastork** [comment]
Also, I should say, I'm using this plugin indirectly via the micronaut plugin.  If I've done the correct digging, the version of this plugin that is used by micronaut is 6.7.0.  So perhaps this is something for them to address by updating to version 7x.

https://github.com/micronaut-projects/micronaut-gradle-plugin

**Comment by Sineaggi** [comment]
It's possible they're still on 6.7.0 to retain java 8 compatibility.

**Comment by bmuschko** [comment]
I am closing this issue for the reasons mentioned above. Thanks for everyone else chiming in.
