### ISSUE TITLE
Too many files opened 

### ISSUE THREAD

**Issue by David-hod** [bmuschko/gradle-docker-plugin#1079]
feels like the code is not closing file descriptors when searching for the main class name. which cause build machine to crash since we dont have that many file descriptors.

Caused by: java.io.FileNotFoundException: /home/ec2-user/workspace/time-it-offers-management/build/classes/scala/main/com/company/offer/service/Service$$typecreator82$2.class (Too many open files)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.bmuschko.gradle.docker.internal.MainClassFinder.doWithMainClasses(MainClassFinder.groovy:131)
	at com.bmuschko.gradle.docker.internal.MainClassFinder.findSingleMainClass(MainClassFinder.groovy:27)
	at com.bmuschko.gradle.docker.internal.MainClassFinder.findSingleMainClass(MainClassFinder.groovy:22)
	at com.bmuschko.gradle.docker.DockerJavaApplicationPlugin.findMainClassName(DockerJavaApplicationPlugin.groovy:43)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin.getApplicationMainClassName(DockerConventionJvmApplicationPlugin.groovy:205)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin.access$1(DockerConventionJvmApplicationPlugin.groovy)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin$2$7.call(DockerConventionJvmApplicationPlugin.groovy:131)
	at com.bmuschko.gradle.docker.DockerConventionJvmApplicationPlugin$2$7.call(DockerConventionJvmApplicationPlugin.groovy)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider

**Comment by bmuschko** [comment]
Any chance you can identify the issue and submit a pull request for this?

**Comment by David-hod** [comment]
sadly, no. this happens on a remote build machine which i don't have access. on my local laptop it work, which is very hard to debug.
also, i am very not so familiar with groovy (mainly scala/java ) 
If you instruct me how to get you more info for investigation, I would do it gladly.

**Comment by David-hod** [comment]
@bmuschko  i see that the code open an Input stream for each `stack.pop` but it never close it, though it's not a main class.
https://github.com/bmuschko/gradle-docker-plugin/blob/a6d7aab2b6a2802ab0069eebc568c0bb51af27cf/src/main/groovy/com/bmuschko/gradle/docker/internal/MainClassFinder.groovy#L131

**Comment by bmuschko** [comment]
Thanks. It will be fixed here: https://github.com/bmuschko/gradle-docker-plugin/pull/1081. Out of curiosity, what's the OS of the machine that produces the error?

**Comment by David-hod** [comment]
We run on linux ec2 xlarge (jenkins)
