### ISSUE TITLE
Macos error Could not start 'docker-credential-desktop'

### ISSUE THREAD

**Issue by zxuanhong** [bmuschko/gradle-docker-plugin#1221]
1. Could not start 'docker-credential-desktop'
2. log info
```
Failure running command ([docker-credential-desktop, list])
Failure when attempting to lookup auth config (configFile: /Users/zxuanhong/.docker/config.json). Falling back to docker-java default behaviour
org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'docker-credential-desktop''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:396)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$3(ExecHandleRunner.java:102)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:101)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'docker-credential-desktop'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:122)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$0(ExecHandleRunner.java:80)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:79)
	... 5 more
Caused by: java.io.IOException: Cannot run program "docker-credential-desktop" (in directory "/Users/zxuanhong/IdeaProjects/anyi-kunpeng/kunpeng-dist"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 10 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 12 more
```
3. build and push can be completed normally. Why??
4. config.json info
<img width="404" alt="image" src="https://github.com/bmuschko/gradle-docker-plugin/assets/62740686/8fadb1b4-9de0-449e-babc-e1728680e82f">

5. Even if the "Could not start" docker-credential-desktop "error can still complete the build and push normally, why not add the configuration to allow users to directly block??
### Your Environment

1. com.bmuschko.docker-remote-api：9.4.0
2. system: macos 14.5 (23F79)
3. docker: 26.1.1
4. jdk: open jdk 21

**Comment by zxuanhong** [comment]
It has been solved, see docker official answer in detail
[docker-credential-helpers 1499](https://github.com/docker/docker-credential-helpers/issues/149)
<img width="802" alt="image" src="https://github.com/bmuschko/gradle-docker-plugin/assets/62740686/d6df9d64-9381-454f-aa8f-52390204c5e7">
