### ISSUE TITLE
java.lang.ClassNotFoundException: org.bouncycastle.openssl.PEMParser

### ISSUE THREAD

**Issue by vskh** [bmuschko/gradle-docker-plugin#144]
Hi gents,

I'm getting following exception when trying to use com.bmuschko.docker-java-application.
Nothing special, mostly copy paste from documentation:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.5'
    }
}
apply plugin:  'com.bmuschko.docker-java-application'
```

Then running gradle 2.8 like this:
`gradlew dockerBuildImage --stacktrace`
gives following exception:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':oauth-authorization-server:dockerBuildImage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/openssl/PEMParser
        at com.github.dockerjava.core.LocalDirectorySSLConfig.getSSLContext(LocalDirectorySSLConfig.java:34)
        at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:148)
        at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130)
        at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
        at com.github.dockerjava.core.DockerClientBuilder$build.call(Unknown Source)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.getDockerClient(DockerThreadContextClassLoader.groovy:90)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.this$2$getDockerClient(DockerThreadContextClassLoader.groovy)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:40)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.openssl.PEMParser
        ... 78 more
```

Tried searching with no luck. Dependency info from gradle yields:
`Using version '1.47' for dependency 'org.bouncycastle:bcpkix-jdk15on:1.51'`

Could you please point on what I might be doing wrong?

**Comment by bmuschko** [comment]
Can you please provide a full build script that reproduces the issue?

**Comment by vskh** [comment]
Hi Benjamin,

It appears that while trying to prepare simple build script reproducing the issue for you I found what causes it to break.

Seems like the plugin is not keeping company with spring.io platform: when I add
```
dependencyManagement {
        imports {
            mavenBom 'io.spring.platform:platform-bom:2.0.1.RELEASE'
        }
    }
```
to build script it breaks with mentioned error. Without this it works fine. I suppose BOM overrides the dependency version used within plugin.

**Comment by bmuschko** [comment]
The dependencies you use shouldn't actually bleed into the dependencies used by Docker Java. The plugin creates its own Classloader for that purpose. That would require a lot of digging and isn't a 5 minute thing to figure out. I don't think I'll be able to look into this in the near future.

**Comment by cdancy** [comment]
@vskh I was able to use the plugin, adding even more dependencies, successfully with the below snippet. Are you doing something non-standard?

```
buildscript() {
	repositories {
        jcenter()
        mavenCentral()
	}
	dependencies {
		classpath "org.jfrog.buildinfo:build-info-extractor-gradle:3.1.1"
		classpath "com.bmuschko:gradle-docker-plugin:2.6.5"
        classpath "io.spring.platform:platform-bom:2.0.1.RELEASE"
	}
}
```

**Comment by cdancy** [comment]
@vskh still having a problem? Were you able to move forward?

**Comment by bmuschko** [comment]
@vskh Please provide us with feedback soon. Otherwise we'll close the issue.

**Comment by vskh** [comment]
Hi gents,

Apologies for not getting back on this, I had to switch to other project.
The problem still exists for me. I am using 'io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE' to import platform bom via following snippet:
```
apply plugin: 'io.spring.dependency-management'
dependencyManagement {
    imports {
        mavenBom 'io.spring.platform:platform-bom:2.0.2.RELEASE'
     }
} 
```

This seems to override the dependencies of docker plugin somehow.

@cdancy, I tried your snippet but it doesn't appear to work for me. Using bom as classpath dependency for build script does not allow to omit the version in dependencies section of project spoiling value of BOM usage. Maybe, I did it wrong? Please, correct me.

To make it easier, I've committed sample project demonstrating issue [here](https://github.com/vskh/docker-gradle-issue-root)

**Comment by eliezio** [comment]
Hi,

A possible fix is to force the bouncycastle libraries version to 1.51+. Just add the line

ext['bouncycastle.version'] = '1.54'

before importing 'io.spring.platform:platform-bom'

**Comment by cdancy** [comment]
@vskh try giving @eliezio suggestion a go. You're stumbling upon another issue that others have noted in that there may be a potential buildscript leak into the plugin classloader.

**Comment by ericweinberg** [comment]
I just wanted to say that @eliezio's suggestion worked for me.

**Comment by vskh** [comment]
Thanks a lot, @eliezio, your recipe indeed works.
As soon as I've got workaround, the issue can be closed.

Thanks.

**Comment by cdancy** [comment]
We have a couple changes on the backlog to help address this issue, and newer yet-to-be-released versions of gradle will also help mitigate this problem some, but until then folks will have to follow the aforementioned solution. If it's not helping feel free to re-open.
