### ISSUE TITLE
Switch default protocol to HTTPS from communication via remote API

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#150]
Docker uses HTTPS as its default protocol. Change the conventions of the plugin to use HTTPS by default. This would require a change in [DockerExtension.groovy](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerExtension.groovy). The property `url` should be switched over to HTTPS, the property `certPath` should use a default location. Documentation needs to be changed accordingly.

**Comment by cdancy** [comment]
+1 though setting the default location for certPath may prove tricky. My experience has been that they are not standard across distributions and if that is the case which do we default to? We could keep a list based on distribution and try to guess the dist at runtime but that feels messy.

**Comment by bmuschko** [comment]
@cdancy I think I saw an implement for this in Docker Java. I guess if we don't provide the `certPath` it will search some default locations. You might want to dig through their code.

**Comment by alan-czajkowski** [comment]
👍

**Comment by alan-czajkowski** [comment]
@bmuschko can you please post what the docker closure example to get it to work with docker v1.11+?

this does not work:
```
docker {
  url = "https://localhost:2375"
}
```

**Comment by cdancy** [comment]
@alan-czajkowski are you providing the `certPath`? Do you have a stacktrace with the exception?

**Comment by alan-czajkowski** [comment]
i'm on OS X

config:
```
docker {
  url = "https://localhost:2375"
}

task buildImage(type: DockerBuildImage) {
//  dependsOn createDockerfile
//  inputDir = createDockerfile.destFile.parentFile
  inputDir = new File("${project.projectDir}/src/main/docker/core-app")
  tag = "some.repo/some.group/some.name:${project.version}"
}
```

ran:
```
$ docker-machine restart
$ eval $(docker-machine env)
$ gradle buildImage
```
and got the following error:
```
:buildImage
Building image using context [redacted]
Using tag [redacted] for image.
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:437)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
	... 25 more
:buildImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> java.lang.reflect.InvocationTargetException-->null
```

**Comment by cdancy** [comment]
Have you tried setting the [certPath](https://github.com/bmuschko/gradle-docker-plugin#extension-properties)?

**Comment by alan-czajkowski** [comment]
tried:
```
docker {
  url = "https://localhost:2375"
  certPath = new File("/Users/alan/.docker/machine/machines/default")
}
```
doesn't help

**Comment by cdancy** [comment]
@alan-czajkowski lets open up a new issue and follow the guidelines set in our [ISSUES](https://github.com/bmuschko/gradle-docker-plugin/blob/master/ISSUES.md) file. This will be much easier than asking a bunch of questions in this enhancement/feature-request issue.

**Comment by alan-czajkowski** [comment]
sorry for polluting this thread, but I found the problem and it's because I was being silly and put ```localhost``` instead of my docker-machine IP

note 1: why isn't this automatically detected by the code and/or [docker-java](https://github.com/docker-java/docker-java) library through some mechanism or either running a docker command to inspecting environment variables? (seems like an easy thing to do)

note 2: i'm running into a problem of using the ```COPY``` command inside my Dockerfile, example:
```
COPY /absolute/path/to/file /absolute/path/inside/image
```
error:
```
...
Step 14 : ENV PATH "${PATH}:${JAVA_HOME}/bin"
---> Using cache
---> c6c1863cc367
Step 15 : COPY /absolute/path/to/file /absolute/path/inside/image
:buildImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> java.lang.reflect.InvocationTargetException-->null

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildImage'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)

```

**Comment by alan-czajkowski** [comment]
i have an idea about [note 2] (see above):
- i'm building using an external Dockerfile:
```
task buildImage(type: DockerBuildImage) {
  inputDir = new File("${project.projectDir}/src/main/docker/core-app")
  tag = "..."
}
```
but i'm referencing a file outside of the docker build context (the directory where the Dockerfile is located)

when i do a ```docker build ...``` on the command-line i get a:
```
Forbidden path outside the build context: ...
```
error when i try to ```COPY``` files that live outside of the current working directory/build context

**Comment by cdancy** [comment]
@alan-czajkowski it sounds like a docker issue to me if I'm not mistaken. Generally you want all of your resources/artifacts to be relative to the Dockerfile itself. They may have changed this requirement as of late.

**Comment by alan-czajkowski** [comment]
i recommend mimicking the behaviour and feature-set of [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin) they have it figured out pretty well, i've used that plugin in the past and am coming up short on trying to find a gradle-equivalent

**Comment by cdancy** [comment]
@alan-czajkowski This plugin builds on top of the [docker-java](https://github.com/docker-java/docker-java) project acting as a wrapper of sorts. If there is an underlying issue with how the building of docker images works, or is implemented, I would open an issue with them.

**Comment by matthiasbalke** [comment]
@bmuschko how about this approach for detecting the local docker configuration
```groovy
if (System.env.DOCKER_HOST) {
    url = "$System.env.DOCKER_HOST".replace("tcp", "https")
    if (System.env.DOCKER_CERT_PATH) {
        certPath = new File(System.env.DOCKER_CERT_PATH)
    }
} else {
    url = 'unix:///var/run/docker.sock'
}
```

I found it in some blog post. I'm not sure which one it was. It works good for me using Docker Toolbox on Windows 8 and native Docker on Ubuntu. I'll try Docker on Mac the next days.

**Comment by cdancy** [comment]
Closing this issue as I don't think it's relevant any longer. Folks can feel free to re-open if they want to discuss this further.
