### ISSUE TITLE
Osx broken pipe

### ISSUE THREAD

**Issue by geoHeil** [bmuschko/gradle-docker-plugin#160]
I get the following error:

```
[pool-9-thread-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://192.168.99.100:2376: Broken pipe
[pool-9-thread-1] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:45)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 18 more
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:876)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:847)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
        at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:169)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:181)
        at org.apache.http.impl.io.SessionOutputBufferImpl.writeLine(SessionOutputBufferImpl.java:221)
        at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:125)
        at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at org.glassfish.jersey.message.internal.ReaderWriter.writeTo(ReaderWriter.java:114)
        at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:77)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:105)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:60)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:301)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:503)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector$2.writeTo(ApacheConnector.java:576)
        at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)

```
 However I have 2 projecs: 

1. NOT using the java application plugin  but no errors e.g. image is created successfully
2. using the java application plugin - this one has the described error. But the correct paths are set:

    ```
if (System.env.DOCKER_HOST) {
        url = "$System.env.DOCKER_HOST".replace("tcp", "https")
        if (System.env.DOCKER_CERT_PATH) {
            certPath = new File(System.env.DOCKER_CERT_PATH)
        }
    } else {
        url = 'unix:///var/run/docker.sock'
    }
```

Docker config is set correctly:
```
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/myname/.docker/machine/machines/default"
```
and I re-generated the certs

**Comment by cdancy** [comment]
@geoHeil for your 1st project: how are you doing things successfully? Through the plugin or command line? Can you successfully invoke the "_ping" endpoint (e.g. https://192.168.99.100:2376/_ping) of the docker daemon and get the 'OK' response?

**Comment by geoHeil** [comment]
I simply use

```
task buildImage(type: DockerBuildImage) {
//    dependsOn createDockerfile, buildDistribution
  dockerFile = project.file('build/Dockerfile')
  inputDir = file("build")
  tag = 'innovation:latest'
}
```

integrated like

```
plugins {
  id "com.moowork.node" version "0.11"
  id "com.moowork.gulp" version "0.11"
  id "com.bmuschko.docker-remote-api" version "2.6.5"
}

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile

apply plugin: 'idea'
apply plugin: 'eclipse'
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'com.moowork.node'
apply plugin: 'com.moowork.gulp'

repositories {
  mavenCentral()
}
```

the ping results in:
```

ping 192.168.99.100
PING 192.168.99.100 (192.168.99.100): 56 data bytes
64 bytes from 192.168.99.100: icmp_seq=0 ttl=64 time=0.313 ms
64 bytes from 192.168.99.100: icmp_seq=1 ttl=64 time=0.284 ms
64 bytes from 192.168.99.100: icmp_seq=2 ttl=64 time=0.412 ms
^C
--- 192.168.99.100 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.284/0.336/0.412/0.055 ms
geoHeil:~ geoHeil$ ping 192.168.99.100:2376
ping: cannot resolve 192.168.99.100:2376: Unknown host
geoHeil:~ geoHeil$ ping 192.168.99.100:2376/_ping
ping: cannot resolve 192.168.99.100:2376/_ping: Unknown host
```

**Comment by cdancy** [comment]
The "ping endpoint" is a docker feature. You have to open your browser, use wget/curl, and hit the URL https://192.168.99.100:2376/_ping. This should return back literally a string saying "OK".

**Comment by geoHeil** [comment]
Unfortunately opening in the browser does not really work as the certificates are not trusted. But trying a `curl 192.168.99.100:2376/_ping`
results in a empty output - no OK

**Comment by cdancy** [comment]
Did you try configuring the docker extension like below?

```
docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File(System.properties['user.home'], '.docker/machine/machines/default')
}
```

**Comment by geoHeil** [comment]
yes.

docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File(System.properties['user.home'], '.docker/machine/machines/default')

        javaApplication {
        baseImage = 'java:8'
        maintainer = 'myname'
        port = 8080
        tag = '/innovation-api:latest'
    }
}

keeps the same error of:

```
 INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://192.168.99.100:2376: Broken pipe
[pool-12-thread-1] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:45)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 18 more
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:876)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:847)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
        at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:169)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:181)
        at org.apache.http.impl.io.SessionOutputBufferImpl.writeLine(SessionOutputBufferImpl.java:221)
        at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:125)
        at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at org.glassfish.jersey.message.internal.ReaderWriter.writeTo(ReaderWriter.java:114)
        at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:77)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:105)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:60)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:301)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:503)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector$2.writeTo(ApacheConnector.java:576)
        at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        ... 20 more
:api:dockerBuildImage FAILED

```

**Comment by cdancy** [comment]
Could you post the full file using the docker extension? There appears to be some discrepancy, at least with your code snippets above, as to how you're using the plugin. Is it possible the certs are no good or need to be renewed?

**Comment by geoHeil** [comment]
My steps
1) renew certificates with docker-machine regenerate-certs --> unfortunately the error persists
2) whole file

here my whole file:
```

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
        classpath "io.spring.gradle:dependency-management-plugin:0.5.5.RELEASE"
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.5'
    }
}

plugins {
    id "org.asciidoctor.convert" version "1.5.3"
}

apply plugin: 'java'

sourceCompatibility = 1.8
targetCompatibility = 1.8

apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'com.bmuschko.docker-java-application'
apply plugin: 'org.asciidoctor.convert'
apply plugin: 'application'
apply plugin: 'war'

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile

jar {
    baseName = 'api'
    version = '0.1.0'
}

repositories {
    mavenCentral()
}

ext {
    snippetsDir = file('build/generated-snippets')
}

test {
    outputs.dir snippetsDir
}

asciidoctor {
    attributes 'snippets': snippetsDir
    inputs.dir snippetsDir
    dependsOn test
}

dependencies {
    compile project(':domain')
    compile project(':database')
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-logging'
    compile 'org.springframework.boot:spring-boot-starter-data-jpa'
    compile 'org.hibernate:hibernate-entitymanager:4.3.11.Final'
    runtime 'com.h2database:h2'
    compile 'org.postgresql:postgresql'
    compile 'org.yaml:snakeyaml:1.16'

    compile('org.springframework.boot:spring-boot-starter-hateoas')
    compile('org.springframework.boot:spring-boot-starter-data-rest')
    compile('org.springframework.data:spring-data-rest-hal-browser')
    compile'org.springframework.boot:spring-boot-devtools'
    compile"org.springframework.boot:spring-boot-starter-actuator"

    testCompile 'org.springframework.boot:spring-boot-starter-test'
    testCompile 'org.springframework.restdocs:spring-restdocs-mockmvc:1.0.1.RELEASE'
    testCompile 'com.jayway.jsonpath:json-path:2.1.0'
}

def springProfile
def versionSuffix
if (project.hasProperty('springProfile')) {
    springProfile = project.property('springProfile')
    versionSuffix = "-" + springProfile
} else {
    springProfile = " "
    versionSuffix = ""
}


docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File(System.properties['user.home'], '.docker/machine/machines/default')

        javaApplication {
        baseImage = 'java:8'
        maintainer = 'myname'
        port = 8080
        //TODO use correct version tagging from GIT
        tag = 'someTag'
    }
}

//docker {
//    if (System.env.DOCKER_HOST) {
//        url = "$System.env.DOCKER_HOST".replace("tcp", "https")
//        if (System.env.DOCKER_CERT_PATH) {
//            certPath = new File(System.env.DOCKER_CERT_PATH)
//        }
//    } else {
//        url = 'unix:///var/run/docker.sock'
//    }
//
//    registryCredentials {
//
//        //TODO load secrets from specialFile
//        // see here http://stackoverflow.com/questions/12749225/where-to-put-gradle-configuration-i-e-credentials-that-should-not-be-committe
//        username = project.hasProperty('dockerHubUsername') ? project.property('dockerHubUsername') : null
//        password = project.hasProperty('dockerHubPassword') ? project.property('dockerHubPassword') : null
//        email = project.hasProperty('dockerHubEmail') ? project.property('dockerHubEmail') : null
//    }
//
//    javaApplication {
//        baseImage = 'java:8'
//        maintainer = 'myname'
//        port = 8080
//        //TODO use correct version tagging from GIT
//        tag = 'someTAg'
//    }
//}

dockerDistTar {
    environmentVariable 'SPRING_PROFILES_ACTIVE', springProfile
}

mainClassName = "someName"

jar {
    dependsOn asciidoctor
    from ("${asciidoctor.outputDir}/html5") {
        into 'static/docs'
    }
}

idea {
    module {
        inheritOutputDirs = false
        outputDir = file("$buildDir/classes/main/")
    }
}

eclipse {
    classpath {
        containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
        containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
    }
}

compileJava.dependsOn(processResources)

```

**Comment by cdancy** [comment]
@geoHeil this can't be it because you're not even applying the plugin anywhere.

**Comment by geoHeil** [comment]
But I use:

```
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'com.bmuschko.docker-java-application'

```

**Comment by cdancy** [comment]
@geoHeil sorry I missed that big section in glancing over things. Are you really using both plugins? You reported issue #154 a couple days ago: were you able to move forward with that? I just would not want to open 10 more issues if we've first not gotten past the first one.

**Comment by geoHeil** [comment]
Yes the other one is closed / works now.
The other project is not using the java application plugin.

**Comment by cdancy** [comment]
Perhaps try and move forward without using the `com.bmuschko.docker-java-application` plugin? Is there something specific you are trying to do there that you can't do with the `com.bmuschko.docker-remote-api` plugin?

**Comment by geoHeil** [comment]
nope - just would be nice if it works.
