### ISSUE TITLE
Failure creating a container - fasterxml - NoSuchMethodError

### ISSUE THREAD

**Issue by edog305** [bmuschko/gradle-docker-plugin#162]
Hi,

I'm able to successfully build an image remotely; however, I'm getting the following error when creating a container from it:

`Execution failed for task ':createContainer'.
com.fasterxml.jackson.databind.ObjectWriter.getJsonFactory()Lcom/fasterxml/jackson/core/JsonFactory;`

Here are some clips from the stack trace:

`Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.ObjectWriter.getJsonFactory()Lcom/fasterxml/jackson/core/JsonFactory;
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
        at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:32)
        at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:14)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:142)
        at com.github.dockerjava.api.command.CreateContainerCmd$exec$0.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.runRemoteCommand(DockerCreateContainer.groovy:148)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:48)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:40)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
`

------------------------------------------------

`Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectWriter.getJsonFactory()Lcom/fasterxml/jackson/core/JsonFactory;
        at com.fasterxml.jackson.jaxrs.json.annotation.EndpointConfig.initWriter(EndpointConfig.java:159)
        at com.fasterxml.jackson.jaxrs.json.annotation.EndpointConfig.forWriting(EndpointConfig.java:63)
        at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider.writeTo(JacksonJsonProvider.java:531)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:301)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:503)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector$2.writeTo(ApacheConnector.java:576)
        at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
`

I tried including a buildscript dependency for com.fasterxml.jackson.core:jackson-databind:2.0.1, but had no luck. Any ideas? Thanks!

**Comment by cdancy** [comment]
@edog305 what do you mean by "build an image remotely"? Are you implying that this somehow works locally? Can you post the gradle script so that we can see what you are doing?

**Comment by edog305** [comment]
@cdancy I'm running Gradle on a Windows machine with boot2docker on a Vagrant box. By "build an image remotely", I mean my Gradle script is using the Docker remote API to build an image on the boot2docker Vagrant host. 

I can post my build script, however it's verbose due to being the default output of JHipster. I'm do little more than create a Docker image based off the tomcat base image, and drop a war file on it. Here is snippet of my gradle-docker-plugin configuration:

task moveDockerFile(type: Copy){
	from 'src/main/docker'
	into 'build/'
}

task buildImage(type: DockerBuildImage) {
	dependsOn moveDockerFile
	tag = 'eric/myimage2'
	inputDir = new File("build/")
}

task createContainer(type: DockerCreateContainer){
	dependsOn buildImage
	targetImageId { buildImage.getImageId() }
	portBindings = ['8080:8080']
}

task runContainer(type: DockerStartContainer) {
	dependsOn createContainer
	targetContainerId { createContainer.getContainerId() }
}

**Comment by edog305** [comment]
I found the same exceptions on the docker-java plugin page: https://github.com/docker-java/docker-java/issues/433

It appears to be in issue in their 2.x versions.

**Comment by cdancy** [comment]
Yea. Looking over things the fix is in their latest 2.2.0 release which we are currently vetting now.

**Comment by edog305** [comment]
Okay. Is there an eta?

Thanks!

**Comment by cdancy** [comment]
@edog305 we are trying to get this change in for the next version that rolls out which hopefully is soon though no ETA. Though not ideal, you could fork this project and do a gradle dependency substitution on the docker-java library to pull in the latest 2.2.0 if you really need to get around things. This would mean hosting your own version in the interim while we flesh things out here. Again, not ideal but it is a solution.

**Comment by bmuschko** [comment]
@edog305 You can already [declare your own dependencies for Docker Java](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy#L52-L58) though there's no guarantee that it actually works with the plugin code.

    configurations {
        dockerJava '...'
    }

@cdancy Maybe worth documenting.

**Comment by bmuschko** [comment]
@edog305 Please try with the latest version of the plugin. Docker Java was upgraded to 2.2.2.

**Comment by bmuschko** [comment]
I am going to close this issue as the Docker Java version used by the plugin was upgraded.
