### ISSUE TITLE
No value has been specified for property 'classpath'.

### ISSUE THREAD

**Issue by Vad1mo** [bmuschko/gradle-docker-plugin#17]
i was able to create an image yesterday. Now if I am trying this again it fails with this stacktrace. I am confused about the error as my code did not change since yesterday.

```
task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
    tag = "vad1mo/myservice"
}
```

```
:createDockerfile UP-TO-DATE
:buildImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':buildImage'.
> No value has been specified for property 'classpath'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':buildImage'.
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:55)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'classpath'.
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
    ... 44 more


BUILD FAILED
``
```

**Comment by jmc-rs** [comment]
org.gradle.api.InvalidUserDataException: No value has been specified for property 'classpath'.
Same issue when  I use the tasks from an external gradle file
using apply from: "${rootProject.projectDir}/../gradle/include/docker.gradle"

**Comment by bmuschko** [comment]
@jmc-rs See solution in #35

**Comment by jmc-rs** [comment]
Yes.. it worked applying the plugin using the full class name..

Thanks a lot

**Comment by jochenchrist** [comment]
This Issue also occurs, when using a buildscript dependency is set in an standalone plugin.

Simple solution would be to simple rename the classpath property in AbstractDockerRemoteApiTask.


in my-docker-plugin.gradle
```
buildscript {
    repositories {
        maven {
...
        }
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.1'
    }
}
```

**Comment by bmuschko** [comment]
@jochenchrist You are not applying the plugin.

**Comment by jochenchrist** [comment]
Thanks, for the quick response. 
Well, i do apply the plugin in my plugin:

my-docker-plugin.gradle
```
buildscript {
    repositories {
        maven {
            url "http://nexus.bv.senacor.com/nexus/content/groups/public"
        }
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.1'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'

...


[define tasks]...
```

In my project build.gradle i apply the my-docker-plugin plugin and i again have to define
```
buildscript {
    repositories {
        maven {
...
        }
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.1'
    }
}
```
as the buildscript is not "exported" with the standalone plugin.

**Comment by bmuschko** [comment]
@jochenchrist Can you please provide a complete example project on Github including the checked-in wrapper?

**Comment by jochenchrist** [comment]
I opened a new issue #116 to further investigate on the exception, as this ticket is closed for a while.
Also I provided some demo code there.
