### ISSUE TITLE
Jackson error pushing to a docker repo

### ISSUE THREAD

**Issue by adrianbk** [bmuschko/gradle-docker-plugin#184]
I'm getting the following stacktrace when pushing an image. The task __does__ complete successfully however.

```
ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "aux" (class com.github.dockerjava.api.model.PushResponseItem), not marked as ignorable (9 known properties: , "stream", "error", "from", "progress", "time", "status", "errorDetail", "id", "progressDetail"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.github.dockerjava.api.model.PushResponseItem["aux"])
  at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
  at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:579)
  at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:672)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:906)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:328)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2769)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1478)
  at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1811)
  at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:48)
  at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
  at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by cdancy** [comment]
@adrianbk when you say the task completed successfully do you mean that the image was successfully pushed to the repo but this was thrown in the back end? Are you executing with '-i' or some other logging level to get this output to show?

**Comment by adrianbk** [comment]
@cdancy yes the image is successfully pushed to the repo. Executing gradle with the `-s -i` switches.

**Comment by cdancy** [comment]
@adrianbk gotcha. This sounds like a bug of sorts with the [docker-java](https://github.com/docker-java/docker-java) project. I'd open an issue with them, reference this one, and see what they say.

**Comment by adrianbk** [comment]
Looks like the fix is already in the latest RC (3+) of the docker-java library https://github.com/docker-java/docker-java/commit/f2954e037ef6be098b1ef838480d61421ed34ceb

**Comment by adrianbk** [comment]
It could probably be patched in this plugin with a Jackson mixin: http://wiki.fasterxml.com/JacksonMixInAnnotations

**Comment by cdancy** [comment]
We would definitely want to wait for docker-java-3.0.0. Seeing as how they already have a fix in for their next release we will just have to wait until then.
