### ISSUE TITLE
Existing Dockerfile, DockerBuildImage task: wildcards in COPY or ADD are not working

### ISSUE THREAD

**Issue by cmoro-deusto** [bmuschko/gradle-docker-plugin#20]
Hi!

   I have a Dockerfile that issues the following command:

```
ADD ./build/libs/*.war /opt/tomcat/webapps/
```
I need that because war files include versioning in the name and change on every build.

I have also defined a DockerBuildImage task on my build.gradle file:

```
task dockerImg(type: DockerBuildImage) {
    dependsOn war
    inputDir = projectDir
    tag = 'test/hi'
}
```

The Dockerfile works correctly if I use the docker cli, but fails if I use gradle to launch the dockerImg task:

```
:dockerImg FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerImg'.
> Source file /Users/carlos/Code/sla/berri/spring/boot/build/libs/*.war doesn't exist
```

I have also tried using COPY instead of ADD and fails in the same way.

Any clues?

Thanks very much in advance.

**Comment by cmoro-deusto** [comment]
Forgot to mention that I have tried using COPY instead of ADD and fails in the same way.

**Comment by cmoro-deusto** [comment]
If anyone is having the same issue, as a workaround, for the moment I just COPY the entire build/libs/ dir:

```
COPY ./build/libs/ /opt/tomcat/webapps/
```

**Comment by bmuschko** [comment]
I am pretty sure that the underlying Docker Java library can't handle the wildcard notation at the moment. Can you run your build with `-s` and add the stack trace?

It's actually very simple to determine the exact path your WAR artifact: `war.archivePath`. Therefore, it's not really necessary to use a wildcard. Keep in mind that you will also want to copy the file you are planning to ADD/COPY into the docker temp. directory first. Otherwise, the ADD/COPY command will fail I believe.

**Comment by cmoro-deusto** [comment]
Hi @bmuschko 

Thanks a lot for your quick reply. 

I have tested the COPY workaround posted above and works without copying it the artifacts to the temp directory.

Running task using ADD with wildcards stack trace:

```
./gradlew dockerImg -s
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:war UP-TO-DATE
:dockerImg
Building image from folder '/Users/carlos/Code/sla/berri/spring/boot'.
:dockerImg FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerImg'.
> Source file /Users/carlos/Code/sla/berri/spring/boot/build/libs/*.war doesn't exist

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dockerImg'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: com.github.dockerjava.api.DockerClientException: Source file /Users/carlos/Code/sla/berri/spring/boot/build/libs/*.war doesn't exist
	at com.github.dockerjava.core.command.BuildImageCmdImpl.buildDockerFolderTar(BuildImageCmdImpl.java:241)
	at com.github.dockerjava.core.command.BuildImageCmdImpl.<init>(BuildImageCmdImpl.java:51)
	at com.github.dockerjava.core.DockerClientImpl.buildImageCmd(DockerClientImpl.java:248)
	at com.github.dockerjava.api.DockerClient$buildImageCmd.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:62)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:49)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:35)
	at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:48)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more


BUILD FAILED
```

Looks like you are right about the Docker Java lib not supporting wildcards (I have also checked the docker-java/docker-java repo and the test for build img don't include ADD or COPY commands on the test Dockerfile). 

I guess I will need to post the issue there ;)

Thanks!!

**Comment by bmuschko** [comment]
OK, sounds good. Please open the issue against the Docker Java library and close this one here.

**Comment by cmoro-deusto** [comment]
OK @bmuschko thanks a lot.

**Comment by cmoro-deusto** [comment]
Just in case you are interested, here is the issue in the Docker Java lib:  https://github.com/docker-java/docker-java/issues/129

**Comment by cmoro-deusto** [comment]
Hi again @bmuschko 

Just FYI:

Docker Java lib fixed the issue: https://github.com/docker-java/docker-java/commit/60fb248a7acc4e6bedbe56503d5ae142862b68f5

This is included in the 0.10.5 version of the lib, which has just been released :)

Cheers

**Comment by bmuschko** [comment]
@cmoro-deusto I am going to bump up the version of Docker Java with the next version of this plugin (0.8.1). Keep in mind that you can also change the dependencies for this plugin in your build script if you want.

Example:

    dependencies {
        dockerJava 'com.github.docker-java:docker-java:0.10.5'
        dockerJava 'org.slf4j:slf4j-simple:1.7.5'
    }

**Comment by cmoro-deusto** [comment]
Thanks a lot for your help  @bmuschko And for your Gradle in Action book!! Happy buyer here ;)
