### ISSUE TITLE
Releasing should update githubpages documentation

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#219]
@bmuschko would you mind ammending the release task to depend on task 'publishGhPages' and, assuming this needs to be done, add the necessary certs/properties to Circle-CI to make publshing them possible?

https://github.com/bmuschko/gradle-docker-plugin/blob/master/gradle/release.gradle#L53

**Comment by cdancy** [comment]
Also ... I planned on cutting a new release tonight (6/5/16). Any thoughts on bumping version to 3.0.0? The release has some big changes and warrants the major version bump IMO.

**Comment by bmuschko** [comment]
> Would you mind ammending the release task to depend on task 'publishGhPages'?

I tried a while ago but couldn't make it work right away with Snap CI. The reason for it is that you'd also need to have another branch for publishing to GHPages. I can try again in the next couple of weeks but probably won't find time to give it a shot today. You can just run it from your local machine in the meantime.

> Any thoughts on bumping version to 3.0.0? 

I'd also bump up the plugin version to a major version.

**Comment by cdancy** [comment]
> I'd also bump up the plugin version to a major version.

That's actually what I was talking about ;)

**Comment by cdancy** [comment]
@bmuschko trying to run 'publishGhPages' from my desktop gives me an auth exception.

Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:bmuschko/gradle-docker-plugin.git: Auth fail
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:83)
        at java_util_concurrent_Callable$call$0.call(Unknown Source)
        at org.ajoberstar.grgit.operation.CloneOp.call(CloneOp.groovy:104)
        ... 69 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:bmuschko/gradle-docker-plugin.git: Auth fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:142)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        ... 74 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:512)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
        ... 81 more

**Comment by cdancy** [comment]
Still can't update docs. Maybe we can set the username/password as properties in the CI job so that we can do something like the below (use this in my own code):


	githubPages {
		repoUri = 'https://github.com/cdancy/artifactory-rest.git'

		pages {
			from(javadoc.outputs.files) {
				into 'docs/javadoc'
			}
		}
		credentials {
			username = project.githubUsername
			password = project.githubPassword
		}
	}

**Comment by bmuschko** [comment]
@cdancy I think that could work but I am not excited about sending my password over the wire. I'd rather not do it.

**Comment by cdancy** [comment]
@bmuschko you could set your username/password as environment variables and we could read it that way as well. I use travis-ci and set the username/password as properties within the job config. Seems like we could do something similar here.

**Comment by cdancy** [comment]
@bmuschko this would also only need to be done on the `release` job so it's not as if others have access to do it and/or see it. Perhaps create a service account to use?

**Comment by bmuschko** [comment]
I was think that we could explore the option of using [javadoc.io](http://javadoc.io/). That might actually be the easier solution anyway.

**Comment by cdancy** [comment]
That's not a bad idea. I've seen more and more projects do the same thing. I can [find only 1 plugin](https://github.com/freefair/javadoc-io-gradle-plugin) that supports this though not sure how active it is and how well it works given the lack of ... anything ;)

**Comment by cdancy** [comment]
Closing but would really love to get this as part of #345 if at all possible.
