### ISSUE TITLE
DockerPullImage tasks fail when executed in parallel

### ISSUE THREAD

**Issue by roberttaylor426** [bmuschko/gradle-docker-plugin#229]
Hi,

I'm experiencing an issue when my build tries to execute two `DockerPullImage` tasks in parallel. My build is multi-project, with parallel task execution enabled, and when the 'pull' tasks execute I get the following error:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':abc:xyz:pullMongoImage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: com.github.dockerjava.api.DockerClientException: Could not pull image: null
        at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:49)
        at com.github.dockerjava.core.command.PullImageResultCallback$awaitSuccess.call(Unknown Source)
        at com.github.dockerjava.core.command.PullImageResultCallback$awaitSuccess.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.image.DockerPullImage.runRemoteCommand(DockerPullImage.groovy:61)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:48)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:43)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath$0.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:53)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
```

The build runs fine if parallel task execution is disabled. 

My task definitions look something like:

```groovy
task pullMongoImage(type: DockerPullImage) {
    repository = "mongo"
    tag = "3.2.4"
}
```

I can work around this issue without too much trouble, but I didn't see anything in the documentation to suggest that parallel task execution might be problematic.

Any ideas? Thanks.

**Comment by cdancy** [comment]
Hey @roberttaylor426! Can you please follow the [guidelines for reporting new issues](https://github.com/bmuschko/gradle-docker-plugin/blob/master/ISSUES.md)?

**Comment by roberttaylor426** [comment]
Apologies, I didn't notice your reporting guidelines.

Actually the problem is resolved now. For anyone else who encounters the same issue, upgrading docker to 1.11.2 solved the problem for me (I was previously using 1.8). FWIW I'm on Ubuntu.

@cdancy as an aside, perhaps you could point users towards your issue reporting guidelines with an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)?

**Comment by cdancy** [comment]
@roberttaylor426 hmmmm ... I actually had that wired up at some point. Not sure why it's not showing up now. Thanks for pointing it out and might explain why the last few folks who submitted issues failed to follow the template ;)
