### ISSUE TITLE
Cannot Push on MacOs

### ISSUE THREAD

**Issue by dilgerma** [bmuschko/gradle-docker-plugin#247]
Hi,

I cannot seem to push an image built with this plugin.

build.gradle:

`
docker {
    url = 'http://192.168.99.100:2376'
}

task copyJar(type: Copy) {
    dependsOn 'jar'
    from "build/libs/${serviceName}-${project.version}.jar"
    into 'build/docker/'
    rename { String fileName ->
        fileName.replace("-${project.version}", "")
    }
}

task createDockerfile(type: Dockerfile) {
    destFile = project.file('build/docker/Dockerfile')
    from 'dilgerm/rpi-app-base'
    addFile "${serviceName}.jar", "/app/application.jar"
    entryPoint "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/application.jar"
}

task docker(type: DockerBuildImage) {
    dependsOn createDockerfile
    dependsOn copyJar
    if (System.env.DOCKER_HOST) {
        url = "$System.env.DOCKER_HOST".replace("tcp", "https")
        if (System.env.DOCKER_CERT_PATH) {
            certPath = new File(System.env.DOCKER_CERT_PATH)

        }
    } else {
        url = 'unix:///var/run/docker.sock'
    }
    inputDir = createDockerfile.destFile.parentFile
    tag = "dilgerm/$serviceName:$project.version"
}
`

If I add this task and try to execute it I get an Exception.

`
task dockerPush(type: DockerPushImage) {
    imageName "dilgerm/$serviceName"
}
`

gradle clean build docker dockerPush results in :

`
Pushing image with name 'dilgerm/billy-time'.
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:437)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 18 more
:dockerPush FAILED
`

Simple Test project:

just clone  https://github.com/dilgerma/billy-rpi-time.git and execute 'gradle build docker dockerPush'.

**Comment by eshepelyuk** [comment]
You're trying to push to registry without pointing the registry and providing credentials.
This can be done by using `registryCredentials` config closure. Please refer to plugin's manual.

PS: as a suggestion, I assume you could drastically simplify your build by leveraging `com.bmuschko.docker-java-application` plugin. 
I.e. no need to generate custom Dockerfile`, no need to custom task for jar copying and building an image.

**Comment by cdancy** [comment]
@dilgerma I'm going to close this for now as I believe @eshepelyuk is correct. Feel free to re-open if you can't get things working by taking the suggestions given.
