### ISSUE TITLE
Please allow provide `containerId` for DockerRemoveContainer task in runtime

### ISSUE THREAD

**Issue by Hubbitus** [bmuschko/gradle-docker-plugin#324]
I want implement two tasks:
* `dockerStart` - which just start application in docker with linked db container. It almost done. And
* `dockerRun` - which plus to `dockerStart` wait user input and on end of gradle build remove created containers and images.

My script looks like:
```gradle
ext.removeContainersOnExit = false
task createEgaisdbContainer(type: DockerCreateContainer, dependsOn: buildEgaisappImage) {
    targetImageId { 'docreg.taskdata.work:5000/egaisdb:latest' }
    containerName "egaisdb_auto_${buildEgaisappImage.buildTagName}"
}
task startEgaisdbContainer(type: DockerStartContainer, dependsOn: createEgaisdbContainer){
    targetContainerId { createEgaisdbContainer.getContainerId() }
}
task createEgaisappContainer(type: DockerCreateContainer, dependsOn: startEgaisdbContainer) {
    targetImageId { buildEgaisappImage.getImageId() }
    containerName = "egaisapp_auto_${buildEgaisappImage.buildTagName}"
    portBindings = [ '8080:8080' ]
    tty = true

    // https://github.com/bmuschko/gradle-docker-plugin/issues/320#issuecomment-270309020
    binds = [ '/sys/fs/cgroup': '/sys/fs/cgroup' ]

    doFirst{
        links = [ "${createEgaisdbContainer.getContainerId()}:egais_db" ]
    }
}
task dockerStart(type: DockerStartContainer, dependsOn: createEgaisappContainer, description: 'create egaisdb and egaisapp linked containers and run both') {
    targetContainerId { createEgaisappContainer.getContainerId() }
}
task dockerRun(dependsOn: dockerStart, description: 'Similar to dockerStart task, but wait keypress to cleanup containers with data'){
    doFirst{
        removeContainersOnExit = true
    }
    doLast{
        System.console().readLine('Press enter to stop and clean');
    }
}

gradle.buildFinished {buildResult ->
    println "Run cleanup buildFinished(). BuildResult: ${buildResult.dump()}"
    removeEgaisappContainer.execute()
    removeEgaisdbContainer.execute()
}

task removeEgaisappContainer(type: DockerRemoveContainer) {
    removeVolumes true
    force true
    doFirst{
        if (removeContainersOnExit && createEgaisappContainer.didWork){
            targetContainerId { createEgaisappContainer.containerName }
            println "Delete created egaisapp container"
            onError { exception ->
                if (!exception.message.contains('No such container')) // ignore exception if container does not exist otherwise throw it
                    throw exception
            }
        }
    }
}
…
```
Problem there I got:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':removeEgaisappContainer'.
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':removeEgaisappContainer'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.execute(AbstractTask.java:334)
        at org.gradle.api.internal.TaskInternal$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at build_aq43n56aofq3g16adz8t2p2m3$_run_closure25.doCall(/home/pasha/Projects/RLH/portal/build.gradle:323)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy13.buildFinished(Unknown Source)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:117)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'containerId'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
        ... 70 more
```

It will be very convenient use gradle `finalizedBy` task dependency, but I should ensure all cleanup performed also on some build fail on any stage.

As you could see there I can't add dependency even like `removeEgaisappContainer.dependsOn createEgaisappContainer` because it is nonsence start container if it was not start early to delete it.

So, I search possibility delete container and do not provide `containerId` on evalution stage.

**Comment by orzeh** [comment]
@Hubbitus as far as I understand your use case it is definitely possible to implement it using Gradle task dependencies and ordering rules - see [docs](https://docs.gradle.org/current/userguide/more_about_tasks.html). I've done it in my own projects.

To fix your issue just move `targetContainerId { createEgaisappContainer.containerName }` outside the `if` and I'll be working:

````groovy
task removeEgaisappContainer(type: DockerRemoveContainer) {
    removeVolumes true
    force true
    targetContainerId { createEgaisappContainer.containerName }
    doFirst{
        if (removeContainersOnExit && createEgaisappContainer.didWork){
            println "Delete created egaisapp container"
            onError { exception ->
                if (!exception.message.contains('No such container')) // ignore exception if container does not exist otherwise throw it
                    throw exception
            }
        }
    }
}
````

We can have a long discussion on how to implement your use case, but it's out of scope of this plugin. Therefore I'm closing this issue.

**Comment by orzeh** [comment]
@Hubbitus @cdancy the script has IMO even more issues, e.g.: `dockerRun` task should have `mustRunAfter dockerStart` because when both task are executed, Gradle _can_ decide to run `dockerRun` __before__ `dockerStart`...

**Comment by Hubbitus** [comment]
> To fix your issue just move targetContainerId { createEgaisappContainer.containerName } outside the if and I'll be working:
No it will not work also if task `createEgaisappContainer` was not run. Please try.

**Comment by Hubbitus** [comment]
@cdancy thank you very much - `onlyIf` seams help there!
