### ISSUE TITLE
DockerBuildIMage on subprojects fails with error `Cannot invoke method withClasspath() on null object`

### ISSUE THREAD

**Issue by seb-koch** [bmuschko/gradle-docker-plugin#387]
I am having an issue that was reported several times in a similar way, e.g. #280 but i wans't able to fix it with the described actions (e.g. different style of loading the plugin).

I have a root project `sitecontroller` which has several docker images to be build in the subfolder `ci/images/<imagename>`. I included these subprojects in my `settings.gradle`

```rootProject.name = 'sitecontroller'
// sub projects for docker images
include 'python-mosquitto', 'sitecontroller-mosquitto'
```

I'd like to reuse my docker tasks (building the image, starting containers and such) for these subprojects insteasd of having individual build files per subdirectory.

My simple build task runs fine for the root project but fails on the subprojects and i believe it is due to the way i am loading the plugin and defining the dependencies. Please see my `build.gradle`below.

```description = 'Bootstrapping'

// import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*

buildscript {
	repositories {
		mavenCentral()
		maven {
			url "https://plugins.gradle.org/m2/"
		}
		repositories {
        jcenter()
    }
	}
	dependencies {
		classpath group: 'net.saliman', name: 'gradle-properties-plugin', version: '1.4.5'
		classpath group: 'com.cinnober.gradle', name: 'semver-git', version: '2.2.+'
		classpath 'com.bmuschko:gradle-docker-plugin:3.0.7'
	}
}
apply plugin: 'net.saliman.properties'
apply plugin: 'com.cinnober.gradle.semver-git'
apply plugin: 'maven-publish'
apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

docker {
	registryCredentials {
			username = dockerRegistryUsername
			password = dockerRegistryPassword
	}
}

ext {
	author = 'azeti Networks AG'
	gitdir = '-C ' + file(".git")
	if (System.env.JENKINS_HOME?.trim()) {
		gitdir = ''
	}
	revision =     "git ${gitdir} rev-list --count HEAD".execute().text.trim()
	hash =         "git ${gitdir} rev-parse --short HEAD".execute().text.trim()
	buildversion = "${revision}#${hash}"
	revltags =     "git ${gitdir} rev-list --tags --max-count=1".execute().text.trim()
	tagversion =   "git ${gitdir} describe --tags ${revltags}".execute().text.trim()
	if (project.hasProperty('gitBranch')) {
		branch = project.getProperty('gitBranch')
	} else {
		branch = "git rev-parse --abbrev-ref HEAD".execute().text.trim()
	}
	buildtime = new Date().format("yyyy-MM-dd' 'HH:mm:ssZ")

	/* master = product releases
	develop = nightly builds, curring edge
	branches = feature or task specific */
	if (branch.equals('master')) {
		// SiteController-install-1.4.0
		dockerTag = "azeti/${project.name}:${version}"
	} else if (branch.equals('develop')) {
		// SiteController-install-develop-1.4.0
		project.version = "develop-${project.version}"
		dockerTag = "azeti/${project.name}:latest"
	} else {
		// SiteController-install-1.4.0-task__SC-914-foo-bar-lorem-ipsum
		ext.snapshotSuffix = branch.replace("/", "__")
		project.version = "${version}-${ext.snapshotSuffix}"
		dockerTag = "azeti/${project.name}:${ext.snapshotSuffix}"
	}

	packageName = "SiteController-install-${project.version}"

	if (System.env.DOCKER_USERNAME) {
		dockerRegistryUsername  = System.env.DOCKER_USERNAME?:dockerRegistryUsername
		dockerRegistryPassword  = System.env.DOCKER_PASSWORD?:dockerRegistryPassword
	}
}

task wrapper(type: Wrapper) {
  gradleVersion = '3.3'
}

allprojects {
	// task build_DockerImage(type: DockerBuildImage, dependsOn: [copy_ImageSource, prepare_ImageConfig]) {
	task build_DockerImage(type: DockerBuildImage) {
		group 'Docker'
		description "Builds the docker image: ${dockerTag} locally"
		println "Project: ${rootProject.projectDir}/ci/images/${project.name}"
		inputDir = file("${rootProject.projectDir}/ci/images/${project.name}")
		tag = dockerTag
	}
}
```

It fails with the known `classPath() on null object`error.

```
root@db8c18347695:/sitecontroller-build# ./gradlew build_DockerImage --stacktrace
Project: /sitecontroller-build/ci/images/sitecontroller
Project: /sitecontroller-build/ci/images/python-mosquitto
Project: /sitecontroller-build/ci/images/sitecontroller-mosquitto
:build_DockerImage
Building image using context '/sitecontroller-build/ci/images/sitecontroller'.
Using tag 'azeti/sitecontroller:task__SC-924-bitbucket-pipelines-build' for image.
Step 1/6 : FROM azeti/python-lib:1
---> e5b575f9797f
Step 2/6 : ENV INSTALL_PATH /opt/azeti
---> Using cache
---> c9718891bb74
Step 3/6 : WORKDIR $INSTALL_PATH
---> Using cache
---> fd8480bd1e74
Step 4/6 : COPY SiteController-install $INSTALL_PATH/SiteController
---> Using cache
---> 02772876fbf4
Step 5/6 : COPY init/docker-entrypoint.sh /
---> Using cache
---> 20388e63fef3
Step 6/6 : ENTRYPOINT /docker-entrypoint.sh
---> Using cache
---> 7f2eee05e1a9
Successfully built 7f2eee05e1a9
Created image with ID '7f2eee05e1a9'.
:python-mosquitto:build_DockerImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':python-mosquitto:build_DockerImage'.
> Cannot invoke method withClasspath() on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':python-mosquitto:build_DockerImage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot invoke method withClasspath() on null object
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runReactiveStream(AbstractDockerRemoteApiTask.groovy:56)
        at com.bmuschko.gradle.docker.tasks.AbstractReactiveStreamsTask.start(AbstractReactiveStreamsTask.groovy:50)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more


BUILD FAILED

Total time: 8.292 secs
```

**Comment by orzeh** [comment]
@seb-koch you didn't apply the plugin to your subprojects?

**Comment by cdancy** [comment]
@seb-koch just to add to what @orzeh said: have you gotten this working in a simple setup first? I would do that to ensure the process works as expected and there are no gotchas with the default setup. Once that works then I would try to make subprojects work but not before.

**Comment by seb-koch** [comment]
I figured this out quickly after posting here. the solution is to apply the plugin right inside of the `allprojects {}` section, this below works good.

```
buildscript {
	repositories {
		mavenCentral()
		maven {
			url "https://plugins.gradle.org/m2/"
		}
		repositories {
        jcenter()
    }
	}
	dependencies {
		classpath group: 'net.saliman', name: 'gradle-properties-plugin', version: '1.4.5'
		classpath group: 'com.cinnober.gradle', name: 'semver-git', version: '2.2.+'
		classpath 'com.bmuschko:gradle-docker-plugin:3.0.7'
	}
}

...

allprojects {
	apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
	    repositories { jcenter() }
	    
	docker {
		registryCredentials {
				username = dockerRegistryUsername
				password = dockerRegistryPassword
		}
	}

  task build_DockerImage(type: DockerBuildImage) {
		group 'Docker'
		description "Builds the docker image: ${dockerTag} locally"
		println "Project: ${rootProject.projectDir}/ci/images/${project.name}"
		inputDir = file("${rootProject.projectDir}/ci/images/${project.name}")
		tag = "azeti/${project.name}:${dockerTag}"
	}```
