### ISSUE TITLE
Building Docker images does not work under Windows

### ISSUE THREAD

**Issue by lreimer** [bmuschko/gradle-docker-plugin#432]
When using the plugin in a Gradle build under Windows the following exception occurs (only snippet):

```
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: java.io.IOException: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1107)
        at com.github.dockerjava.core.util.CompressArchiveUtil.archiveTARFiles(CompressArchiveUtil.java:105)
        at com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:135)
        ... 92 more
        Suppressed: java.io.IOException: This archives contains unclosed entries.
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:225)
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:241)
                at com.github.dockerjava.core.util.CompressArchiveUtil.archiveTARFiles(CompressArchiveUtil.java:109)
                at com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:135)
```

The bug is probably not in the plugin itself, but rather in the `docker-java` library the plugin is using. The `IOException` tells me that someone has locked a file the library wants to use. The Dockerfile references a file from within the Gradle `build/` directory, so it is probably Gradle that holds the lock.

This bug only happens under Windows, when I run the exact same build on my Mac everything is OK.
I tried latest Gradle 4.x as well as Gradle 3.4, no difference. Tried building with and without the Gradle daemon, no difference.

If you need a project to reproduce, use https://github.com/lreimer/everything-as-code

Similar issues and stacktraces have been reported in #5 and #295

**Comment by cdancy** [comment]
@lreimer I would an open ISSUE with the `docker-java` guys, link to this ISSUE, and see what they have to say.

**Comment by lreimer** [comment]
OK. I will open an additional issue with `docker-java` team and link it.

**Comment by lreimer** [comment]
@cdancy I have some feedback from the `docker-java` community. Unfortunately, nothing really seems to help. I tried narrowing down the build context using `.dockerignore` to only the TAR file produced by the application plugin I want to include in the Docker image. No luck 😒 

I could copy the TAR and the Dockerfile somewhere outside the `$projectDir` but that somehow defeates the objective of the plugin and a self-contained build.

Why is Gradle under Windows so aggressively locking files and directories? Is this a platform behaviour?
So for now, this behaviour renders the plugin unusable under Windows.

**Comment by orzeh** [comment]
@lreimer it's strange that `.dockerignore` didn't help. Try setting `buildDir` as an `inputDir` property in `BuildDockerImage` task. This will require to add task that will copy `Dockerfile` inside `buildDir`.

That being said I will switch to Windows and play with your project to see if I can reproduce it and fix.

**Comment by lreimer** [comment]
@orzeh Thanks for this one. Moving the `Dockerfile` into `$buildDir` does the trick.

**Comment by lreimer** [comment]
Just for completeness, here is the solution:
```groovy
task copyDockerfile(type: Copy) {
    from 'Dockerfile'
    into buildDir
}

task buildDockerImage(type: DockerBuildImage) {
    inputDir = buildDir
    tag = "${project.name}:${project.version}"
}

buildDockerImage.dependsOn copyDockerfile
```

**Comment by orzeh** [comment]
@lreimer ok, I reproduced it on Windows and indeed found a bug in `docker-java` 😄 but in `.dockerignore` handling. Directories that start with `.` like `.git` are not properly excluded. I'm pretty sure that `.git` folder was messing in your case.

I will prepare a fix and link here for tracking.

**Comment by orzeh** [comment]
@lreimer I'm closing it as it is not this plugin bug and you finally found working solution. When fix to `docker-java` will be released and used here, it will be possible to also resolve it with ignoring directories/files.

**Comment by lreimer** [comment]
Thanks. I will wait for the fix to be available in the next `docker-java` version.
