### ISSUE TITLE
ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback

### ISSUE THREAD

**Issue by ksambhav** [bmuschko/gradle-docker-plugin#468]
I am trying to workout a simple docker build on a Ubuntu 17.04 machine : -

```
import com.bmuschko.gradle.docker.tasks.DockerVersion
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

docker {
    url = 'unix:///var/run/docker.sock'
}

task dockerVersion(type: DockerVersion)

task dockerBuild(type: DockerBuildImage) {
    dependsOn dockerVersion
    inputDir = file(".")
    tag = 'my-app' + project.version
}
```
While executing 'dockerBuild' task getting this exception : - 

```
> Task :dockerVersion
Retrieving Docker version.
Version          : 17.06.2-ce
Git Commit       : cec0b72
Go Version       : go1.8.3
Kernel Version   : 4.10.0-33-generic
Architecture     : amd64
Operating System : linux


[dockerjava-jaxrs-async-0] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Connection reset by peer at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@2d2bcd0a; file=/run/docker.sock; connected=true; bound=false]
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
.
.
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:108)
.
.
Caused by: java.io.IOException: Connection reset by peer at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@2d2bcd0a; file=/run/docker.sock; connected=true; bound=false]
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXOutputStream.write(AFUNIXSocketImpl.java:260)
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Connection reset by peer
        at org.newsclub.net.unix.NativeUnixSocket.write(Native Method)
  
```
`com.bmuschko:gradle-docker-plugin:3.1.0`

I am also using the IntelliJ docker plugin which seems to be working fine while using the default unix socket.  How to correctly configure the plugin to use the same ?

**Comment by orzeh** [comment]
@ksambhav I've tried to reproduce this issue without success. Could you provide an example build script that fails?

**Comment by ksambhav** [comment]
Not sure why, it seems to be working now when I try...   
Closing the issue.
