### ISSUE TITLE
Tag repository limited to 30 characters

### ISSUE THREAD

**Issue by mkjois** [bmuschko/gradle-docker-plugin#469]
When I tag something with a repository part (not counting after `:`) greater than 30 characters, I get the following exception. I would write something to reproduce but it should be self-explanatory.

IIRC this was increased officially by Docker to 255 characters (see https://github.com/moby/moby/pull/11118), but maybe the Docker API or docker-java library is still unhappy with it?

```
[dockerjava-jaxrs-async-0] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Broken pipe at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@78526e30; file=/Users/mjois/Library/Containers/com.docker.docker/Data/s60; connected=true; bound=false]
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 18 more
Caused by: java.io.IOException: Broken pipe at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@78526e30; file=/Users/mjois/Library/Containers/com.docker.docker/Data/s60; connected=true; bound=false]
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXOutputStream.write(AFUNIXSocketImpl.java:260)
        at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
        at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:179)
        at org.apache.http.impl.io.SessionOutputBufferImpl.writeLine(SessionOutputBufferImpl.java:219)
        at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:123)
        at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:179)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at org.glassfish.jersey.message.internal.ReaderWriter.writeTo(ReaderWriter.java:116)
        at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:79)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:105)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:60)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:300)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:517)
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:499)
        at org.glassfish.jersey.apache.connector.ApacheConnector$2.writeTo(ApacheConnector.java:583)
        at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        ... 20 more
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Broken pipe
        at org.newsclub.net.unix.NativeUnixSocket.write(Native Method)
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXOutputStream.write(AFUNIXSocketImpl.java:251)
        ... 50 more
```

**Comment by cdancy** [comment]
@mkjois what version of the plugin are you using?

**Comment by orzeh** [comment]
@mkjois here is my test `build.gradle`:

````gradle
//....
version = '0.0.1-SNAPSHOT'
import com.bmuschko.gradle.docker.tasks.*

task buildImage(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage){
    inputDir = file('.')
    tag = 'dockerimage' * 10 +':' + version
}
````

and the console output:
````console
sample-app$ gradle buildImage
Step 1/1 : FROM alpine:3.5
---> 37c7be7a096b
Successfully built 37c7be7a096b
Successfully tagged dockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimage:0.0.1-SNAPSHOT

> Task :buildImage
Building image using context '/home/orzeh/projekty/sample-app'.
Using tag 'dockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimagedockerimage:0.0.1-SNAPSHOT' for image.
Created image with ID '37c7be7a096b'.


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
````

**Comment by mkjois** [comment]
Damn, sorry false alarm. My problem was that the repository part has can't have uppercase characters. I guess the only concern is that the error message is far from indicative of the problem...only reason I thought the problem might have been the character limit is because of another issue that related to it.
