### ISSUE TITLE
"invalid tag format" when publishing image to docker registry

### ISSUE THREAD

**Issue by NorrinRadd** [bmuschko/gradle-docker-plugin#475]
We've tried every variation of the below that we can think of.  DockerPushImage always fails with:

> Pushing image with name 'build_d591ev4owt93tilp7yk0c2gbk$_run_closure19$_closure31@5632ace9'.
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"invalid tag format"}

        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
:pushToRegistry FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pushToRegistry'.
> {"message":"invalid tag format"}

task buildImage(type: DockerBuildImage) {
    tags = ['group/platform-router'].toSet()
    inputDir = file('.')
}

task pushToRegistry(type: DockerPushImage) {
    dependsOn   stopMyAppContainer
    imageName = { buildImage.getTags[0] }

    // Have tried all of the below lines one by one
    tag       = 'group/platform-router:latest'
    tag       = 'platform-router:latest'
    tag       = { buildImage.getTags[0] }
    tag       = { buildImage.getTag }

    // The below results in this error: > Could not push image: An image does not exist locally with the tag: null
    tag       = 'latest'
}

The image name that it's attempting to push looks weird.  Perhaps there is a problem regarding that.   It's unclear what format the plugin wants the tag to be in.  What would work here?

**Comment by orzeh** [comment]
@NorrinRadd I know it's a little bit confusing. Let me explain it on an example:

````gradle
task buildDockerImage(type: DockerBuildImage) {
	inputDir = file('.')
	tag = "docker.registry.com:5000/some_user/${project.name}:${project.version}"
}

task pushDockerImage(type: DockerPushImage, dependsOn: 'buildDockerImage') {
	imageName = "docker.registry.com:5000/some_user/${project.name}"
	tag = project.version
}
````

In build image task a `tag` or `tags` property should contain image name and tag (and image registry if needed). However in push image task, the `tag` property contains only actual tag (i.e. 'latest', '3.0.1' and so on) and remaining information is set via `imageName` property (registry, user, image name).

Hope it's clear now.

BTW we may add this to our Wiki page.
