### ISSUE TITLE
DockerWaitHealthyContainer throws exception

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#518]
My task for verifying the health check fails with the exception below.

```
task waitOnHealthyContainer(type: DockerWaitHealthyContainer) {
    group = 'Docker'
    mustRunAfter startContainer
    targetContainerId { createContainer.getContainerId() }
}
```

Could it be that the Docker Java version got out-of-date or is not compatible with the latest version of Docker? I am using Version 17.12.0-ce-mac49 (21995).

```
> Task :waitOnHealthyContainer FAILED
Waiting for container with ID '4adb593414eecfb5aae710fc4b95832a7a21d80ccb3a8f7428a81ef94a345772' to be healthy.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':waitOnHealthyContainer'.
> Cannot get property 'status' on null object
```

The stack trace is here:

```
Caused by: java.lang.NullPointerException: Cannot get property 'status' on null object
        at com.bmuschko.gradle.docker.tasks.container.extras.DockerWaitHealthyContainer.check(DockerWaitHealthyContainer.groovy:62)
        at com.bmuschko.gradle.docker.tasks.container.extras.DockerWaitHealthyContainer.runRemoteCommand(DockerWaitHealthyContainer.groovy:47)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_runReactiveStream_closure1.doCall(AbstractDockerRemoteApiTask.groovy:57)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:55)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runReactiveStream(AbstractDockerRemoteApiTask.groovy:56)
        at com.bmuschko.gradle.docker.tasks.AbstractReactiveStreamsTask.start(AbstractReactiveStreamsTask.groovy:47)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

**Comment by orzeh** [comment]
@bmuschko I don't see any [API changes](https://docs.docker.com/engine/api/version-history/) in this context. I'll try to reproduce it on my machine.

**Comment by cdancy** [comment]
@bmuschko @orzeh finally had a chance to look into this. Yeah it looks like the returned json is thus (exact same setup as Ben):

```
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 24802,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-01-25T18:45:07.045068882Z",
            "FinishedAt": "2018-01-25T14:30:24.469696608Z"
        },
```

To preserve backwards compatibility we could wrap things in a try/catch block and do something like this:

```
String healthStatus
try {
    healthStatus = state.health.status
} catch (NullPointerException npe) {
    if (npe.message.contains('Cannot get property') {
        healthStatus = state.status
    } else {
        throw npe
    }
}

if (onNext) {
    onNext(healthStatus)
}
```

**Comment by bmuschko** [comment]
@cdancy Thanks for looking into it. Sounds reasonable.

**Comment by cdancy** [comment]
@bmuschko need a new point release once this goes through?

**Comment by bmuschko** [comment]
@cdancy That would be great!

**Comment by cdancy** [comment]
Version `3.2.3` has been released.

**Comment by bmuschko** [comment]
Nice, thanks guys!
