### ISSUE TITLE
AFUNIXSocket sometimes throws UnsatisfiedLinkError when buildImage run with --parallel

### ISSUE THREAD

**Issue by nhoughto** [bmuschko/gradle-docker-plugin#523]
We use this plugin to build docker images from our Gradle tasks and have been seeing non-deterministic failures due to what looks like a race condition in `junixsocket`, i'm pretty sure its due to a race condition in a library `docker-java` uses and an issue has been raised. I'm leaving this here for the next person who has this problem when using this plugin. The error thrown is this:

```
Caused by: java.lang.ExceptionInInitializerError
    at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
    at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
    at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:51)
    at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:66)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
    at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
    at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
    at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
    at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
    at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:42)
    ... 26 more
Caused by: java.lang.reflect.InvocationTargetException
    at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
    ... 26 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libjunixsocket-native-2.0.42131647397275370483.so: Error loading shared library /tmp/libjunixsocket-native-2.0.42131647397275370483.so: No such file or directory
    at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:39)
    ... 27 more
```

Library issue:
https://github.com/kohlschutter/junixsocket/issues/45

**Comment by cdancy** [comment]
@nhoughto yeah we get this here randomly but on all types of unix machines (mac and linux). Usually a reboot clears things up if it pops more than once. I've not spent any significant amount of time looking into this so I'm not sure what to make of it.

**Comment by petehayes** [comment]
Just got this again this week.

`21:38:55 Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
21:38:55 	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:42)
21:38:55 	... 83 more
21:38:55 Caused by: java.lang.reflect.InvocationTargetException
21:38:55 	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
21:38:55 	... 83 more
21:38:55 Caused by: java.lang.UnsatisfiedLinkError: /tmp/libjunixsocket-native-2.0.48850897867219105446.so: /tmp/libjunixsocket-native-2.0.48850897867219105446.so: cannot open shared object file: No such file or directory
21:38:55 	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:39)
21:38:55 	... 84 more`

**Comment by cdancy** [comment]
@petehayes did you hit this on your desktop or in a CI environment?

@nhoughto long shot but do you remember where you ran things when you hit this issue?

**Comment by petehayes** [comment]
This was on a CI environment.
