### ISSUE TITLE
DockerBuild task fails when it needs to pull from a private registry

### ISSUE THREAD

**Issue by edmeister** [bmuschko/gradle-docker-plugin#545]
I ran into an issue when trying to build a dockerfile that extends an image from a private registry. Internally we use a Nexus docker registry, but I was able to reproduce with a private image on Docker Hub.

Steps to reproduce:

1. Create a dockerfile that starts with a pull from a private registry. E.g. `FROM private/image`. Of course the image cannot be present on the local machine.

2. Create a gradle build with a DockerBuildImage and a DockerPullImage task.

```groovy
docker {
    registryCredentials {
        url = "https://index.docker.io/v1/"
        username = "cloudnativesbe"
        password = "******"
        email = "jeroen@cloudnatives.be"
    }
}

task pullImage(type: DockerPullImage) {
    repository = "private/image"
}

task buildImage(type: DockerBuildImage) {
    tags = [ "some-tag" ]
    inputDir = file('.')
}
```

3. The DockerPullImage task runs successfully. The DockerBuildImage task fails with

```
> Task :buildImage 
Task ':buildImage' is not up-to-date because:
  Task has not declared any outputs.
Running in a non-OSGi environment
Building image using context '.'.
Using Dockerfile 'Dockerfile'
Using tags 'test' for image.

:buildImage (Thread[Task worker for ':',5,main]) completed. Took 2.974 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> Could not build image: pull access denied for cloudnativesbe/demo, repository does not exist or may require 'docker login'

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildImage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: pull access denied for cloudnativesbe/demo, repository does not exist or may require 'docker login'
        at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
        at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
        at java_lang_reflect_Method$invoke.call(Unknown Source)
        at java_lang_reflect_Method$invoke.call(Unknown Source)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$_createPrintStreamProxyCallback_closure12.doCall(DockerThreadContextClassLoader.groovy:574)
        at com.sun.proxy.$Proxy851.invoke(Unknown Source)
        at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$e7793ba6.awaitImageId(<generated>)
        at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$e7793ba6$awaitImageId.call(Unknown Source)
        at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$6357555c$awaitImageId.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:161)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_runReactiveStream_closure1.doCall(AbstractDockerRemoteApiTask.groovy:57)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:55)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runReactiveStream(AbstractDockerRemoteApiTask.groovy:56)
        at com.bmuschko.gradle.docker.tasks.AbstractReactiveStreamsTask.start(AbstractReactiveStreamsTask.groovy:50)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more

```

**Comment by orzeh** [comment]
@edmeister can you put `registryCredentials {}` inside `buildImage` task and see if it helps?

**Comment by edmeister** [comment]
I tested with the task below, but got the same output.

```
task buildImage(type: DockerBuildImage) {
    tags = [ "test" ]
    inputDir = file('.')

    def credentials = new DockerRegistryCredentials()
    credentials.setUsername("cloudnativesbe")
    credentials.setPassword("********")

    registryCredentials = credentials
}
```

**Comment by orzeh** [comment]
@edmeister did you specify `url`?

**Comment by edmeister** [comment]
@orzeh it falls back to the default url, which is `https://index.docker.io/v1`. Setting it explicitly gives the same outcome. I just verified.

**Comment by edmeister** [comment]
For the record: I circumvented the issue by creating an extra task that parses my dockerfile, strips out the image part from the `FROM ...` line and does a docker pull of that image.

**Comment by orzeh** [comment]
@edmeister can you check this with plain `docker-java`? It would help nail down the issue.

**Comment by edmeister** [comment]
Hmm, not really familiar with that package, but I can try.

**Comment by orzeh** [comment]
@edmeister please take a look at the test https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/cmd/BuildImageCmdIT.java#L197

**Comment by cdancy** [comment]
@edmeister you may want to have a look at @jfmoy response as this is the expected way to do things and how we do things here as well. I didn't think this was a point of confusion but perhaps it is so?

**Comment by edmeister** [comment]
Definitely no confusion, but maybe it's resolved with a newer version of docker-java.

When I filed the issue, I could easily reproduce both with a private repository (also a nexus setup) and with a private image on Docker hub. 

I'll retry later on and give feedback.

**Comment by edmeister** [comment]
@cdancy the issue still exists. I could reproduce with a private image on Docker Hub and an image on our private Nexus registry. 
The only difference is that @jfmoy uses a Dockerfile task, while all our projects have explicit docker files.

So for clarity, this is the exact code I used to reproduce. 

build.gradle
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.3.3'
    }
}


apply plugin: 'com.bmuschko.docker-remote-api'

import com.bmuschko.gradle.docker.tasks.image.*

docker {
    registryCredentials {
        url = "${dockerRegistryUrl}"
        username = "${dockerRegistryUser}"
        password = "${dockerRegistryPassword}"
        email = "${dockerRegistryEmail}"
    }
}

task test(type: DockerBuildImage) {
    inputDir = file('.')
    tag = 'test/myapp:latest'
}
```
Dockerfile
``` 
FROM cloudnativesbe/demo

```

The credentials I used, are of course correct.

**Comment by cdancy** [comment]
It's the `FROM cloudnativesbe/demo` that looks off but it _may_ be correct. So for us, and when hitting our internal artifactory docker registry, our from would look like: 

`FROM machine.company.com:7000/database:123`.

**Comment by edmeister** [comment]
That is definitely correct. There is no other way to address a private image on the Docker hub.

**Comment by cdancy** [comment]
Conversation has died down here so closing issue. Feel free to re-open should you want to discuss things anymore.

**Comment by artemananiev** [comment]
I've just faced the same issue. Having spent a couple hours trying this and that, I found that in my case the problem was that docker credentials "url" property didn't have "https://" prefix. May be this is your case, too...

**Comment by SinghDivneet** [comment]
I am running into a similar issue to pull an image from harbor & defining the following does nothing for me.


```
docker {
  registryCredentials {
    url = ironbankDockerRegistryUrl
    username = ironbankDockerRegistryUsername
    password = ironbankRegistryPassword
    email = ironbankDockerRegistryEmail
  }
}
```

The task below is where I want to use the said registry credentials 

```
task ubidockerBuildImage(type: DockerBuildImage) {
  description = 'Builds an image using the Docker daemon for the current build.'
  dependsOn UBIsyncDockerBuildContext
  inputDir = file(dockerBuildContextDir)
  dockerFile = file("${dockerBuildContextDir}/UBI/Dockerfile")
  buildArgs = ['DPM_VERSION': version, 'BUILD_NUMBER': buildNumber == null ? '1' : buildNumber, 'GIT_REVISION' : "${revision}"]
  images = ["${dockerImageName}:${version}-ubi"]
}
```
