### ISSUE TITLE
bump javax.activation to 1.1.1 to make docker build work on java 10?

### ISSUE THREAD

**Issue by likewhatevs** [bmuschko/gradle-docker-plugin#570]
When using java 10 and running docker build, the following exception is thrown:
```
    The following warnings have been detected: WARNING: HK2 service reification failed for [com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
    MultiException stack 1 of 2
    java.lang.NoClassDefFoundError: javax/activation/DataSource
```
I worked around this by compiling the plugin locally with the following:
```
compile('javax.activation:activation:1.1.1'){
     force = true
}
```
I'm not sure if that's a good way to go about making this plugin work on java 10, but it worked for me.

**Comment by cdancy** [comment]
Interesting... Is this reproducible on other OS's? What version of our plugin are you using?

**Comment by cdancy** [comment]
Thanks @edmeister. Very strange. I can of course add this to the list of required deps and/or bake this into our `docker-java-shaded` lib if necessary just seems very odd is all.

**Comment by edmeister** [comment]
Very easy snippet to reproduce.

```
➜  gradle-bug java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

➜  gradle-bug cat build.gradle 
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.6'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'

import com.bmuschko.gradle.docker.tasks.image.*

task test(type: DockerBuildImage) {
    inputDir = file('.')
    tag = 'test/myapp:latest'
}
```
After running `gradle test` we get lots of these stacktraces

```
WARNING: HK2 service reification failed for [com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2316)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1310)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1306)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1306)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1249)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:144)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:178)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:128)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:179)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:723)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:678)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:458)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2205)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:122)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1350)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1345)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:116)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1407)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1332)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1321)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:187)
	at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:222)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:772)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
	at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
	at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 66 more
MultiException stack 2 of 2
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
	implementation=com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.DataSourceProvider
	contracts={com.github.dockerjava.shaded.javax.ws.rs.ext.MessageBodyWriter,com.github.dockerjava.shaded.javax.ws.rs.ext.MessageBodyReader}
	scope=com.github.dockerjava.shaded.javax.inject.Singleton
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=com.github.dockerjava.shaded.org.glassfish.hk2.utilities.binding.AbstractBinder$2@19bbb336
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=12
	locatorId=4
	identityHashCode=1581626354
	reified=false)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:689)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:458)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2205)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:122)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1350)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1345)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:116)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1407)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1332)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1321)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:187)
	at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:222)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at com.github.dockerjava.shaded.org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:772)
	at com.github.dockerjava.shaded.org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
	at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
	at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by cdancy** [comment]
@orzeh ... interesting. Not sure if we should handle this new dep or docker-java.

**Comment by cdancy** [comment]
Yeah you're probably right. Wouldn't be too bad to add this additional dependency to our plugin/config. I guess my main concern was adding it to the `docker-java-shaded` library which would in turn put it out of sync with upstream `docker-java` but if we add it here it should be fine. If the user is on an earlier version of java it should amount to a no-op. Let me throw something together now.

**Comment by cdancy** [comment]
Created PR #572 to address this.

**Comment by cdancy** [comment]
Just released version `3.2.7` with a change to resolve this issue. Can folks on this thread give things a go and let me know how you fare?

**Comment by cwensel** [comment]
3.2.7 `DockerBuildImage` just worked for me on Java 10. It didn't yesterday on 3.2.6. 

Thanks!

**Comment by cdancy** [comment]
Very good and thanks @cwensel ! Closing this issue.

**Comment by qgicup** [comment]
Worked for me as well with version 3.2.7
