### ISSUE TITLE
Error when pushing to Docker Registry 2.0

### ISSUE THREAD

**Issue by jugalps** [bmuschko/gradle-docker-plugin#59]
I get following error when trying to push a Docker Registry 2.0. I have changed the value of dockerRegistryUrl to point it to v2 registry, however it seems internally, you are still expecting it to be sent to v1 registry:
```
docker {
    registryCredentials {
        url = "http://$dockerRegistryUrl/v2/myapp"
    }
}
```

You can refer to registry 2.0 API [here](http://docs.docker.com/registry/spec/api/).
```
Caused by: com.github.dockerjava.api.InternalServerErrorException:  v1 ping attempt failed with error: Get https://foo.bar.corp:5000/v1/_ping: Forbidden. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry mo-603021cfa.mo.sap.corp:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/mo-603021cfa.mo.sap.corp:5000/ca.crt

        at com.github.dockerjava.core.util.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:54)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
        at com.github.dockerjava.jaxrs.PushImageCmdExec.execute(PushImageCmdExec.java:44)
        at com.github.dockerjava.jaxrs.PushImageCmdExec.execute(PushImageCmdExec.java:28)
        at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
        at com.github.dockerjava.core.command.PushImageCmdImpl.exec(PushImageCmdImpl.java:65)
        at com.github.dockerjava.api.command.PushImageCmd$exec$0.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.image.DockerPushImage.runRemoteCommand(DockerPushImage.groovy:64)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:48)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:37)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 56 more
```

**Comment by bmuschko** [comment]
Looks like [Docker Java](https://github.com/docker-java/docker-java) doesn't support V2 yet. Would you mind opening the issue over there? I won't be fixed until the underlying library supports it.
