### ISSUE TITLE
Exception cglib

### ISSUE THREAD

**Issue by jonbom** [bmuschko/gradle-docker-plugin#604]
I am getting an exception when building an image.

### Current Behavior
```
Execution failed for task ':webservice:buildDockerImage'.
> class net.sf.cglib.core.DebuggingClassWriter has interface org.objectweb.asm.ClassVisitor as super class
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':webservice:buildDockerImage'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IncompatibleClassChangeError: class net.sf.cglib.core.DebuggingClassWriter has interface org.objectweb.asm.ClassVisitor as super class
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:231)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:149)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:117)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:109)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:105)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:71)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.createPrintStreamProxyCallback(DockerThreadContextClassLoader.groovy:575)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.createBuildImageResultCallback(DockerThreadContextClassLoader.groovy:396)
	at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$createBuildImageResultCallback.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:160)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_runReactiveStream_closure1.doCall(AbstractDockerRemoteApiTask.groovy:51)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withContext(DockerThreadContextClassLoader.groovy:57)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$withContext.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:56)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runReactiveStream(AbstractDockerRemoteApiTask.groovy:50)
	at com.bmuschko.gradle.docker.tasks.AbstractReactiveStreamsTask.start(AbstractReactiveStreamsTask.groovy:47)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 30 more

```

### Steps to Reproduce (for bugs)
Don't really know what is causing the problem, because other projects are working, but it seems to be a problem with version clash for cglib.

### Your Environment
Gradle 4.8

**Comment by jonbom** [comment]
@orzeh I am using 3.3.5

**Comment by jonbom** [comment]
It is a matter of leaking classpath in gradle...

**Comment by jonbom** [comment]
Would it be possible to use the [shadow plugin](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow) to shadow the shaded docker library?

**Comment by cdancy** [comment]
@jonbom we already do that through use of the docker-java-shaded library:

https://github.com/project-aries/docker-java-shaded

**Comment by jonbom** [comment]
Then some of the classes dont get shaded.

**Comment by cdancy** [comment]
@jonbom what exactly do you mean by shaded here and what are you expecting? Did you open the library/jar itself to inspect its contents? Are you seeing other libraries/dependencies resolved through gradle which should in fact be within this library?

**Comment by jonbom** [comment]
@cdancy I mean that I get a class collition because I load cglib (and indirectly asm) to run a wadl2java code generation. I would not get that collition if all dependent libraries for the (excellent btw) docker-plug-in would have been shadowed (changed packet structure).

**Comment by bigpuritz** [comment]
getting the same error with **gradle-docker-plugin:3.3.6**.

is there any solution for this?

**Comment by bigpuritz** [comment]
as far as i can see, there are conflicting asm-dependencies in my project:

dockerJava - Configuration:

```
dockerJava - The Docker Java libraries to be used for this project.
+--- com.aries:docker-java-shaded:3.0.14
+--- org.slf4j:slf4j-simple:1.7.5
|    \--- org.slf4j:slf4j-api:1.7.5 -> 1.7.25
+--- javax.activation:activation:1.1.1
\--- cglib:cglib:3.2.0
     +--- org.ow2.asm:asm:5.0.3
     \--- org.apache.ant:ant:1.9.4
          \--- org.apache.ant:ant-launcher:1.9.4
```

runtime - Configuration:

```
...
     +--- org.eclipse.jetty.websocket:javax-websocket-server-impl:9.4.10.v20180503
     |    +--- org.eclipse.jetty:jetty-annotations:9.4.10.v20180503
     |    |    +--- org.eclipse.jetty:jetty-plus:9.4.10.v20180503
     |    |    |    \--- org.eclipse.jetty:jetty-webapp:9.4.10.v20180503 (*)
     |    |    +--- org.eclipse.jetty:jetty-webapp:9.4.10.v20180503 (*)
     |    |    +--- javax.annotation:javax.annotation-api:1.2 -> 1.3.2
     |    |    +--- org.ow2.asm:asm:6.1.1
     |    |    \--- org.ow2.asm:asm-commons:6.1.1
     |    |         +--- org.ow2.asm:asm:6.1.1
     |    |         +--- org.ow2.asm:asm-tree:6.1.1
     |    |         |    \--- org.ow2.asm:asm:6.1.1
     |    |         \--- org.ow2.asm:asm-analysis:6.1.1
     |    |              \--- org.ow2.asm:asm-tree:6.1.1 (*)
...
```

**Comment by cdancy** [comment]
Can folks put together a reproducible snippet that I can give a go? You can always force the correct dependency through gradle across the board.

**Comment by cdancy** [comment]
I see this for both runtime and compile when I attempt to list the dependencies of an arbitrary project with this dependency:
```
runtime - Runtime dependencies for source set 'main' (deprecated, use 'runtimeOnly ' instead).
+--- com.aries:docker-java-shaded:3.0.14
\--- com.aries:gradle-docker-application-plugin:0.9.0
     \--- com.bmuschko:gradle-docker-plugin:3.3.3

runtimeClasspath - Runtime classpath of source set 'main'.
+--- com.aries:docker-java-shaded:3.0.14
\--- com.aries:gradle-docker-application-plugin:0.9.0
     \--- com.bmuschko:gradle-docker-plugin:3.3.3

```
Furthermore when I open the intellij IDE I don't see any extra dependencies being brought in from cglib either. I would need a reproducible project/snippet to be able to further debug.

**Comment by bigpuritz** [comment]
[demo-docker.zip](https://github.com/bmuschko/gradle-docker-plugin/files/2131041/demo-docker.zip)

this is the demo project where you can see the issue. this is a simple springboot/vaadin application.
as far as i can see, the problem occurs only if i add **gradle-vaadin-plugin** to the build.gradle. without the plugin the generation of the docket image works well.

**Comment by cdancy** [comment]
@bigpuritz Ok now I see where the potential problem is coming from. I was being thrown off by talk of `dockerJava` and the `docker-java-shaded` library but really it's the configuration we build at runtime which has the older cglib config which in turn is bringing in the older asm:
```
        Configuration config = project.configurations[DOCKER_JAVA_CONFIGURATION_NAME]
        config.defaultDependencies { dependencies ->
            dependencies.add(project.dependencies.create("com.aries:docker-java-shaded:$DockerRemoteApiPlugin.DOCKER_JAVA_DEFAULT_VERSION"))
            dependencies.add(project.dependencies.create('org.slf4j:slf4j-simple:1.7.5'))
            dependencies.add(project.dependencies.create('javax.activation:activation:1.1.1'))
            dependencies.add(project.dependencies.create('cglib:cglib:3.2.0'))
        }
```
Mulling some things around as to how we can best solve this...

**Comment by cdancy** [comment]
The change here appears to be on our end in that newer versions of cglib/asm have changes in types (interface to class) that need to be accounted for here I just haven't had time to look into things yet assuming I'm right. cglib/asm are finicky libraries and it may be that we need to shadow those deps here. @orzeh any thoughts to that?

**Comment by orzeh** [comment]
@cdancy we may update `cglib` version, but it _may_ break existing build scripts. On the other hand maybe we should start to plan version 4 of this plugin and do it there?

**Comment by cdancy** [comment]
As of version `3.4.2` cglib is now shaded within our plugin and should cause no more issues for users.
