### ISSUE TITLE
Remove all deprecations

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#675]
### Expected Behavior

Remove all deprecated fields and methods in this plugin. It's the perfect time to do this with a major release of the plugin.

### Current Behavior

We still have a bunch of old, deprecated code that has been around for ages.

### Context

Clean up the code base. Ensure that consumers now use the desired APIs.

**Comment by bmuschko** [comment]
@cdancy Any chance you'll have some time to tackle this?

**Comment by cdancy** [comment]
@bmuschko I can look things over in the next couple days.

**Comment by bmuschko** [comment]
@bmuschko I suggest we get this done and then release or new version. Alternatively, we'll leave it in remaining deprecations and release now.

**Comment by cdancy** [comment]
There are a few that can be removed but it will be the weekend before I can sit with things and make sure everything works correctly.

**Comment by bmuschko** [comment]
@cdancy OK, thanks. I already had a brief look at it. It'll be more work than you think as the usability for end users will be quite different e.g. for `DockerBuildImage.getTag()`. ;-)

Maybe we just release as-is for now. Would love to get those feature out.

**Comment by bmuschko** [comment]
@cdancy BTW: That one functional test (`autoRemove`) is still failing intermittently. We should get to the bottom of it.

**Comment by cdancy** [comment]
We could release now if you're up for it.

As for the `autoRemove` thing ... no idea. Maybe that will go away when we move to the other docker java library. IDK.

**Comment by bmuschko** [comment]
> We could release now if you're up for it.

Let's do it! Can you take care of it?

> As for the autoRemove thing ... no idea. Maybe that will go away when we move to the other docker java library. IDK.

I am going to revisit sometime next week. It also occurred once on my machine. I have the feeling that there's just something wrong with the test case.

**Comment by cdancy** [comment]
I can certainly knock it out. Stay tuned...

**Comment by cdancy** [comment]
@bmuschko so trying to run `./gradlew release -Prelease.stage=final -Prelease.scope=major` I get the below:
```
Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.kotlin.dsl.GroovyInteroperabilityKt$delegateClosureOf$1.doCall() is applicable for argument types: (org.ajoberstar.gradle.git.release.base.ReleaseVersion) values: [org.ajoberstar.gradle.git.release.base.ReleaseVersion(4.0.0, 3.6.2, true)]
Possible solutions: doCall(), call(), call([Ljava.lang.Object;), call(java.lang.Object), findAll(), equals(java.lang.Object)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:71)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:77)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:183)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:587)
        at org.ajoberstar.gradle.git.release.base.TagStrategy.maybeCreateTag(TagStrategy.groovy:78)
        at org.ajoberstar.gradle.git.release.base.TagStrategy$maybeCreateTag.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at org.ajoberstar.gradle.git.release.base.BaseReleasePlugin$_addReleaseTask_closure4_closure6.doCall(BaseReleasePlugin.groovy:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:739)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:712)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
```

**Comment by cdancy** [comment]
@bmuschko I _think_ you may have missed something :) Trying a few things out now.

**Comment by cdancy** [comment]
@bmuschko Ok we got a release out ... but the job ultimately failed due to attempting to publish to maven central. Probably just a config that was missed. Poking around for that now. In either event 4.0.0 was published successfully.

**Comment by cdancy** [comment]
Oh ... you have sync to maven central set to true. I assume this was on purpose then?

```

> Task :bintrayPublish FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bintrayPublish'.
> Could not sync '[secure]/gradle-plugins/com.[secure]:gradle-docker-plugin/4.0.0' to Maven Central: HTTP/1.1 400 Bad Request [message:Please enter your Sonatype OSS credentials.]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bintrayPublish'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

**Comment by bmuschko** [comment]
@cdancy Thanks, I think the credentials were wrong. I checked them again and re-entered them into Travis as environment variables. I'll have a deeper look if this happens again upon the next release. Also touched up some things for the documentation publishing code.

**Comment by bmuschko** [comment]
@cdancy Did you make any progress on removing some of the deprecations?

**Comment by cdancy** [comment]
@bmuschko been away on vacation and have _tried_ to stay offline as much as possible. Haven't looked at this yet. Just catching up on things now. I'll try to get some time in over the next few days.

**Comment by bmuschko** [comment]
@cdancy This is blocking a couple of things. We start working on it soon. Do you think you'll have the time?

**Comment by bmuschko** [comment]
@cdancy I just did it.
