### ISSUE TITLE
DockerBuildImage in 4.0.0 no longer compatible with Gradle 4.7

### ISSUE THREAD

**Issue by jkuipers** [bmuschko/gradle-docker-plugin#685]
Upgraded our project, which uses Gradle 4.7 at the moment, to version 4.0.0 of the plugin and ran a task extending `DockerBuildImage`. This results in the following error (left out irrelevant parts of the output):
```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [class 'com.bmuschko.gradle.docker.DockerRemoteApiPlugin']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:150)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:129)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:130)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:114)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$100(DefaultObjectConfigurationAction.java:38)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$2.run(DefaultObjectConfigurationAction.java:77)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
        at org.gradle.groovy.scripts.DefaultScript.apply(DefaultScript.java:128)
        at org.gradle.api.Script$apply.callCurrent(Unknown Source)
        at docker_27ibc1s6zgcifhq7gy3309nau.run(C:\repos\NLO\Dev\services\gradle\docker.gradle:13)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 117 more
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.bmuschko.gradle.docker.DockerExtension_Decorated.
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:53)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.plugins.DefaultConvention.instantiate(DefaultConvention.java:251)
        at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:144)
        at com.bmuschko.gradle.docker.DockerRemoteApiPlugin.apply(DockerRemoteApiPlugin.groovy:49)
        at com.bmuschko.gradle.docker.DockerRemoteApiPlugin.apply(DockerRemoteApiPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        ... 127 more
Caused by: java.lang.NoSuchMethodError: org.gradle.api.file.ProjectLayout.configurableFiles([Ljava/lang/Object;)Lorg/gradle/api/file/ConfigurableFileCollection;
        at com.bmuschko.gradle.docker.DockerExtension.<init>(DockerExtension.groovy:35)
        at com.bmuschko.gradle.docker.DockerExtension_Decorated.<init>(Unknown Source)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        ... 143 more
```

Apparently the new code relies on a (version of the) `configurableFiles` method that isn't available in 4.7. I saw that Gradle 4.3 is mentioned as the minimum supported version, so I guess this should be considered as a bug.

**Comment by bmuschko** [comment]
Thanks for letting us know. You are correct. The Gradle minimal version is 4.8 for plugin v4.0.0 because we are using `ProjectLayout#configurableFiles(Object...)`. I was not aware that it was introduced with a later version of Gradle. At the moment we don't run any cross-version compatibility tests to ensure the minimal Gradle version as it would take far too long to execute the suite against Docker multiple times.

I corrected and re-published the documentation.
