### ISSUE TITLE
IOException on DockerBuildImage Task

### ISSUE THREAD

**Issue by fseebach** [bmuschko/gradle-docker-plugin#689]
Running the following DockerBuildImage Task throws an IOException:

`task createDockerfile(type: Dockerfile) {
    destFile = project.file('build/Dockerfile')
    from 'ubuntu:12.04'
}

task buildDockerImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.get().asFile.parentFile
    tag = 'bmuschko/myimage:latest'

}`

Stacktrace:
`org.gradle.api.UncheckedIOException: java.io.IOException: Die Syntax f├╝r den Dateinamen, Verzeichnisnamen oder die Datentr├ñgerbezeichnung ist falsch
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:686)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getOutputPaths(DefaultTaskExecutionPlan.java:770)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.resolveMutations(DefaultTaskExecutionPlan.java:611)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getResolvedMutationInfo(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNext(DefaultTaskExecutionPlan.java:552)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:174)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:161)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:161)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.io.IOException: Die Syntax f├╝r den Dateinamen, Verzeichnisnamen oder die Datentr├ñgerbezeichnung ist falsch
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:681)
        ... 12 more`

I had to Debug Gradle to see whats going on here.
The exception happens in 
DefaultTaskExecutionPlan:681

Gradle tries to resolve the following path:
`F:\*******\build\.docker\:buildDockerImage-imageId.txt`
That fails with an IOException because of the ":"

### Your Environment
Gradle 4.10.2
gradle-docker-plugin 4.0.1
Windows

**Comment by cdancy** [comment]
Hmmm... There was recent changes made by @bmuschko in this area. This works in testing. Maybe an OS specific issue? Either way I can take a look in a bit.

**Comment by bmuschko** [comment]
I have been using the task path to create the file name. Apparently, Windows cannot deal with a trailing colon character in the file name. The logic should probably strip the first colon character and replace all other colon characters with an underscore.
