### ISSUE TITLE
Wait on container startup

### ISSUE THREAD

**Issue by Sledzik** [bmuschko/gradle-docker-plugin#691]
Hi, I would like to ask if this [#381](https://github.com/bmuschko/gradle-docker-plugin/issues/381) solution is still valid? I use version 4.0.2 of plugin with gradle wrapper 4.10 and mentioned solution doesn't work for me.
My task looks like that:

    task waitForDB2ContainerStartup(type: DockerLogsContainer) {
     dependsOn startDB2Container
     targetContainerId createDB2Container.getContainerId()
     follow.set(true)
     tailAll.set(true)
     onNext { message ->
        def logMessage = message.toString()
        println logMessage
        if (logMessage.contains("DB20000I")) {
            throw new RuntimeException('DB2 CONTAINER-STARTED')
        }
     }
     onError { exception ->
        println("onError")
        if (!exception.message.contains('DB2 CONTAINER-STARTED')) {
            throw exception
        }
     }
     onComplete { complete ->
        println("onComplete")
     }
    }

I noticed that gradle does not stop _waitForDB2ContainerStartup_ task so logs following is still ongoing. What is also strange to me that I do not see in logs my _onError_ message.

**Comment by Sledzik** [comment]
STDOUT: DB20000I  The CREATE DATABASE command completed successfully.
     Exception thrown inside enhancer callback when invoking method createOnNextProxyCallback
      java.lang.RuntimeException: DB2 CONTAINER-STARTED
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at      sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at  org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callCons tructor(ConstructorSite.java:105)
        at  org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
        at build_21kjky4v9i8jfrr9upx4ll0ps$_run_closure29$_closure34.doCall(...\build.gradle:303)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at  org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.api.Action$execute.call(Unknown Source)
        at  com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$_createOnNextProxyCallback_closure13.doCall(DockerThreadContextClassLoader.groovy:582)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at  org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:54)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
        at com.sun.proxy.$Proxy137.invoke(Unknown Source)
        at  com.github.dockerjava.core.command.LogContainerResultCallback$$EnhancerByCGLIB$$70b2d614.onNext(<generated>)
        at  com.github.dockerjava.jaxrs.AbstrAsyncDockerCmdExec$1.onNext(AbstrAsyncDockerCmdExec.java:43)
        at  com.github.dockerjava.core.async.FrameStreamProcessor.processResponseStream(FrameStreamPr ocessor.java:31)
        at  com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:66)
        at  com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    STDOUT: Could not load host key: /etc/ssh/ssh_host_rsa_key
    STDOUT: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
    STDOUT: Could not load host key: /etc/ssh/ssh_host_ed25519_key
    <===========--> 90% EXECUTING [3m 27s]
    > :waitForDB2ContainerStartup
     > IDLE

**Comment by bmuschko** [comment]
@cdancy You may want to look at this as you more familiar with the callbacks.

**Comment by Sledzik** [comment]
It turned out that the problem was that I used Docker Machine on Windows. When I switched to native Docker on Linux, the problem disappeared.

By the way, I realized that there is DockerLivenessContainer which simplifies everything a lot.

**Comment by cdancy** [comment]
@Sledzik yeah that's the way to go. You can also take a look at the gradle-docker--databases-plugin at project-aries which has a ton of helper functionality to stand up databases and builds on top of this plugin.
