### ISSUE TITLE
Cannot buildImage for SpringBoot 2 with plugin version 3.4+ - error ClassNotFoundException: com.github.dockerjava.shaded.net.sf.cglib.proxy.Enhancer

### ISSUE THREAD

**Issue by zpapez** [bmuschko/gradle-docker-plugin#713]
### Expected Behavior
Even with plugin versions 3.4+ that brought shading of `cglib`, I should be able to buildImage of SpringBoot 2.

### Current Behavior
```
Caused by: java.lang.ClassNotFoundException: com.github.dockerjava.shaded.net.sf.cglib.proxy.Enhancer
        at java_lang_ClassLoader$loadClass.call(Unknown Source)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.loadClass(DockerThreadContextClassLoader.groovy:150)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.createPrintStreamProxyCallback(DockerThreadContextClassLoader.groovy:600)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.createBuildImageResultCallback(DockerThreadContextClassLoader.groovy:397)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$createBuildImageResultCallback.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:178)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_runReactiveStream_closure1.doCall(AbstractDockerRemoteApiTask.groovy:53)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withContext(DockerThreadContextClassLoader.groovy:60)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$withContext.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:58)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runReactiveStream(AbstractDockerRemoteApiTask.groovy:52)
        at com.bmuschko.gradle.docker.tasks.AbstractReactiveStreamsTask.start(AbstractReactiveStreamsTask.groovy:46)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

### Context
When I use plugin version `3.3.6` the same image builds OK.

### Steps to Reproduce (for bugs)
See branch of sample project at https://github.com/zpapez/gradle-docker-plugin-spring-boot-2/tree/shaded

### Your Environment
- gradlew 4.10.3
- fails both if my JDK is 1.8 or openjdk11

**Comment by bmuschko** [comment]
You can pretty much delete all of your code by just using the [specific Spring Boot plugin](https://bmuschko.github.io/gradle-docker-plugin/#spring_boot_application_plugin). I'd recommend going with that one.

As a side note: You not using the shaded library of Docker Java. You are just using the unshaded one: [`com.github.docker-java:docker-java:3.1.0-rc-7`](https://github.com/zpapez/gradle-docker-plugin-spring-boot-2/blob/shaded/build.gradle#L36).

**Comment by zpapez** [comment]
Thanks, I had to use the shaded java library with cglib included as a dependency:
`dockerJava 'com.aries:docker-java-shaded:3.1.0-rc-5:cglib@jar'`
It is now working with plugin version `3.6.2` or `4.1.0`.
https://github.com/zpapez/gradle-docker-plugin-spring-boot-2

Thank you for the hint.
