### ISSUE TITLE
What's changed between 3.6.2 and 4.1.0 with DockerCreateContainer

### ISSUE THREAD

**Issue by hirowla** [bmuschko/gradle-docker-plugin#721]
Hi,

I was wondering what has changed between release 3.6.2 and 4.1.0 in regard to DockerCreateContainer? I've just tried to upgrade with an unchanged build.gradle and an unchanged Gradle (it's 4.9) and now my DockerCreateContainer task no longer works. I now get the following error message - "No value has been specified for this provider"

The task definition is as follows (after removing confidential stuff):

```
task createAppContainer(type: DockerCreateContainer) {

    targetImageId { 'registry.azurecr.io/project/manager'}
    portBindings = ['8098:8098', '8008:8000']
    binds = ["/opt/project/manager": "/runtime"]
    restartPolicy = 'unless-stopped'
    hostName = '172.16.135.12'
    containerName = project.name
    // Comment the line below out if you wish to turn off debug
    env = ["JVM_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"]
}

```

Any ideas what has changed between the versions, and what needs to be fixed? 

Thanks.

**Comment by bmuschko** [comment]
The version range you mention spans a couple of versions. You see what changed in the [change log](https://bmuschko.github.io/gradle-docker-plugin/#change_log). The most prominent change is likely the introduction of the `Provider` API. You'll have to provide us the stack trace so we know where in the code it breaks. You might have to assign a value to a property that became mandatory.

**Comment by bmuschko** [comment]
OK, we'll still need to see the stack trace though which can be created with the command line option `-s`. I think it would be the easiest if you could provide us with a reproducible, minimal example as a GitHub repository + the checked in Gradle Wrapper.

**Comment by hirowla** [comment]
Here is the stack trace running against 4.1.0 (the trace is slightly different for 4.0.0 but just a different line). Gradle is definitely 4.9.
(Trimmed off the first bit because it only refers to Gradle).

```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at org.gradle.api.provider.Provider$get$0.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer$_setContainerCommandConfig_closure1.doCall(D
ockerCreateContainer.groovy:318)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.setContainerCommandConfig(DockerCreateContai
ner.groovy:316)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.runRemoteCommand(DockerCreateContainer.groov
y:230)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTa
sk.groovy:63)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withContext(DockerThreadContextClassLoader.gr
oovy:61)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$withContext.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask
.groovy:110)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:62)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuil
dOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuil
dOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.j
ava:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:99)
        ... 31 more
```

**Comment by bmuschko** [comment]
The issue seems to the [handling of an already deprecated property called `env`](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy#L315-L319). You should use the replacement property `envVars`. Either way you shouldn't see the issue. I will completely remove the `env` property with the next release.

**Comment by bmuschko** [comment]
Remove the `env` property: https://github.com/bmuschko/gradle-docker-plugin/commit/1c556abababe76c9d29e8569a9535f2ee500d35d
