### ISSUE TITLE
dockerPushImage uses username in place of tagname

### ISSUE THREAD

**Issue by m410** [bmuschko/gradle-docker-plugin#748]
I created a project with the Kotlin-dsl and want to push my image to our repository.  Creating the image works as expected, but when I try to push it appears to be looking for the a tag based on username.  I changed articatoryUser and it outputs the different username.  Am I missing some configuration?

```
docker {

    registryCredentials {
        val space = if (version.toString().endsWith("SNAPSHOT")) "develop" else "release"
        val artifactoryUser: String by project
        val artifactoryPass: String by project

        url.set("${dockerBase}/${space}/")
        username.set(artifactoryUser)
        password.set(artifactoryPass)
        email.set("user@company.com")
    }

    springBootApplication {
        baseImage.set("openjdk:11.0.2-slim-stretch")
        ports.set(listOf(8080, 8443))
        tag.set("benjamin:${project.version}")
    }
}
```

```
> gradle :benjamin:dockerPushImage -PartifactoryUser=cliuser -PartifactoryPass=clipass
executing gradlew instead of gradle

> Task :benjamin:dockerBuildImage
Building image using context '/Users/mike.fortin/Projects/Fiserv/multitenant/benjamin/benjamin/build/docker'.
Using tags 'benjamin:0.4.0' for image.

Step 1/7 : FROM openjdk:11.0.2-slim-stretch

---> 20be262dd659
Step 2/7 : WORKDIR /app

---> Using cache
---> a6f1bb00e9a4
Step 3/7 : COPY libs libs/

---> Using cache
---> a00aada3375f
Step 4/7 : COPY resources resources/

---> Using cache
---> 541c333dfbbb
Step 5/7 : COPY classes classes/

---> Using cache
---> 9d0c0b0e83fb
Step 6/7 : ENTRYPOINT ["java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.fiserv.cbs.benjamin.micro.Application"]

---> Using cache
---> 9fd7a1bd0a53
Step 7/7 : EXPOSE 8080 8443

---> Using cache
---> e5deeb3ca5c5
Successfully built e5deeb3ca5c5
Successfully tagged benjamin:0.4.0

> Task :benjamin:dockerBuildImage
Created image with ID 'e5deeb3ca5c5'.

> Task :benjamin:dockerPushImage FAILED
Pushing image with name 'benjamin:0.4.0'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':benjamin:dockerPushImage'.
> Could not push image: An image does not exist locally with the tag: cliuser

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
8 actionable tasks: 2 executed, 6 up-to-date
multitenant/benjamin [develop●] » docker images
REPOSITORY                                                                     TAG                   IMAGE ID            CREATED             SIZE
benjamin                                                                       0.4.0                 e5deeb3ca5c5        About an hour ago   526MB
```

```
gradle --version
executing gradlew instead of gradle

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
OS:           Mac OS X 10.14.3 x86_64
```

**Comment by bmuschko** [comment]
Can you run this with `-s`? I'd like to see the stack trace.

I think what's happening here is that the image tag has to reflect the repository you want to push it to. For example, on DockerHub my username is `bmuschko` which corresponds with the list repositories at `https://cloud.docker.com/u/bmuschko/repository/list`. Artifactory likely follows the same convention. You will probably want to use a tag format like `<username-or-registry-on-artifactory>/<image-name>:<version>`. I personally haven't tried out pushing to Artifactory with the plugin yet so I can't give you any deeper insight at the moment.

**Comment by m410** [comment]
Thanks for the quick reply, here's the output:
```
gradle -s :benjamin:dockerPushImage -PartifactoryUser=some-unknown-user -PartifactoryPass=not-a-password
executing gradlew instead of gradle

> Task :benjamin:dockerBuildImage
Building image using context '/Users/mike.fortin/Projects/Fiserv/multitenant/benjamin/benjamin/build/docker'.
Using tags 'benjamin:0.4.0' for image.

Step 1/7 : FROM openjdk:11.0.2-slim-stretch

---> 20be262dd659
Step 2/7 : WORKDIR /app

---> Using cache
---> a6f1bb00e9a4
Step 3/7 : COPY libs libs/

---> Using cache
---> a00aada3375f
Step 4/7 : COPY resources resources/

---> Using cache
---> 541c333dfbbb
Step 5/7 : COPY classes classes/

---> Using cache
---> 9d0c0b0e83fb
Step 6/7 : ENTRYPOINT ["java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.fiserv.cbs.benjamin.micro.Application"]

---> Using cache
---> 9fd7a1bd0a53
Step 7/7 : EXPOSE 8080 8443

---> Using cache
---> e5deeb3ca5c5
Successfully built e5deeb3ca5c5
Successfully tagged benjamin:0.4.0

> Task :benjamin:dockerBuildImage
Created image with ID 'e5deeb3ca5c5'.

> Task :benjamin:dockerPushImage FAILED
Pushing image with name 'benjamin:0.4.0'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':benjamin:dockerPushImage'.
> Could not push image: An image does not exist locally with the tag: some-unknown-user

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':benjamin:dockerPushImage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
        at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not push image: An image does not exist locally with the tag: some-unknown-user
        at com.github.dockerjava.core.command.PushImageResultCallback.throwFirstError(PushImageResultCallback.java:40)
        at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:91)
        at com.github.dockerjava.core.command.PushImageResultCallback.awaitSuccess(PushImageResultCallback.java:53)
        at com.github.dockerjava.core.command.PushImageResultCallback$awaitSuccess.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.image.DockerPushImage.runRemoteCommand(DockerPushImage.groovy:64)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withContext(DockerThreadContextClassLoader.groovy:61)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$withContext.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:110)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
        ... 32 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
8 actionable tasks: 2 executed, 6 up-to-date

```
I took a brief look at the source, was wondering if it was related to https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPlugin.groovy line 145.  Could that be returning null on push?  Just a guess. thx again

**Comment by m410** [comment]
Not how I missed this, but this works
```
docker {
    registryCredentials {
        val artifactoryUser: String by project
        val artifactoryPass: String by project
        username.set(artifactoryUser)
        password.set(artifactoryPass)
    }

    springBootApplication {
        val space = if (version.toString().endsWith("SNAPSHOT")) "develop" else "release"
        baseImage.set("openjdk:11.0.2-slim-stretch")
        ports.set(listOf(8080, 8443))
        tag.set("${dockerBase}/${space}/implementato:${project.version}")
    }
}
```

**Comment by bmuschko** [comment]
Great, glad you could figure it out.
