### ISSUE TITLE
binds no longer working in DockerCreateContainer task

### ISSUE THREAD

**Issue by gjvoosten** [bmuschko/gradle-docker-plugin#758]
As of version `4.6.0`, `binds` in a `DockerCreateContainer` task are no longer working.
### Expected Behavior

The relevant portion of the failing Gradle task is:
```
task dockerCreateDB(type: com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer) {
        […]
        binds = ["${projectDir}":"/hostdata"] + run.environment.get("DOCKER_MOUNTS", [:])
        […]
}
```
With version `4.5.0` the binds work as intended.

### Current Behavior

An exception is thrown:
```
> Task :dockerCreateDB FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerCreateDB'.
> Could not find matching constructor for: com.github.dockerjava.api.model.Bind(java.util.LinkedHashMap$Entry)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dockerCreateDB'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
[…]
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.github.dockerjava.api.model.Bind(java.util.LinkedHashMap$Entry)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer$_setContainerCommandConfig_closure7.doCall(DockerCreateContainer.groovy:402)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.setContainerCommandConfig(DockerCreateContainer.groovy:402)
        at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.runRemoteCommand(DockerCreateContainer.groovy:245)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:70)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
[…]
```
### Context

:smiley: I'd be happy if the binds were working again.

### Steps to Reproduce (for bugs)

There isn't a test case in Git, but if I make e.g. the following change in `master`:
```
diff --git a/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy b/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
index cd54271..8e89ec7 100644
--- a/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
+++ b/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
@@ -29,6 +29,7 @@ class DockerCreateContainerFunctionalTest extends AbstractGroovyDslFunctionalTes
                 targetImageId pullImage.getImageId()
                 cmd = ['groups']
                 groups = ['postgres']
+                binds = ['/tmp':'/testdata']
             }
         """
         buildFile <<
```
and run `./gradlew functionalTest`, I get a similar stacktrace.

### Your Environment

Bug is present in `com.bmuschko:gradle-docker-plugin:4.6.0`; it is working correctly in the previous release `com.bmuschko:gradle-docker-plugin:4.5.0`.

**Comment by bmuschko** [comment]
Thanks for reporting. TIL that `@CompileStatic` is not inherited in subclasses. Will work on a fix soon.

**Comment by bmuschko** [comment]
This has been released. Probably takes a while for the Gradle plugin portal to sync with JCenter.

**Comment by gjvoosten** [comment]
I can confirm that the binds work again with `4.6.1`. Thanks for the rapid response, @bmuschko!
