### ISSUE TITLE
Error copying a directory from container to host

### ISSUE THREAD

**Issue by rkrisztian** [bmuschko/gradle-docker-plugin#783]
I've prepared a demo project that records a video of the VNC session provided by https://github.com/elgalu/docker-selenium (see attachment [test-docker-selenium.zip](https://github.com/bmuschko/gradle-docker-plugin/files/3038447/test-docker-selenium.zip)). Then tried to copy a folder from the container to the host, which fails.

### Expected Behavior
Copying should just work. I could of course use a mount bindings, but directory sharing takes more configuration effort, thus I'd rather have both features work (i.e. being able to choose copying or sharing directories).

### Current Behavior
```
$ docker rm -f $(docker ps -a -q); gw test

> Task :pullSeleniumImage
Pulling repository 'elgalu/selenium'.

> Task :createSeleniumContainer
Created container with ID '9e9c9e63e307cba5a611eb4cc8653dae863833604849aa5fb6b22e4f31ff8e02'.

> Task :startSeleniumContainer
Starting container with ID '9e9c9e63e307cba5a611eb4cc8653dae863833604849aa5fb6b22e4f31ff8e02'.

> Task :inspectSeleniumContainer
Inspecting container with ID '9e9c9e63e307cba5a611eb4cc8653dae863833604849aa5fb6b22e4f31ff8e02'.

> Task :stopSeleniumVideo
Executing on container with ID '9e9c9e63e307cba5a611eb4cc8653dae863833604849aa5fb6b22e4f31ff8e02'.
total 132K
-rw-r--r-- 1 seluser seluser 131K Apr  3 13:37 vid_chrome_25550_firefox_25551.mp4

> Task :findSeleniumVideos
Executing on container with ID '9e9c9e63e307cba5a611eb4cc8653dae863833604849aa5fb6b22e4f31ff8e02'.
**** Output is printed above for some reason.

> Task :copySeleniumVideos FAILED
Copying '/videos/' from container with ID '9e9c9e63e307cba5a611eb4cc8653dae863833604849aa5fb6b22e4f31ff8e02' to '/home/rkrisztian/test-docker-selenium/build/videos'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':copySeleniumVideos'.
> Error closing message content input stream.
```

From the stacktrace:

```
Caused by: com.bmuschko.gradle.docker.shaded.javax.ws.rs.ProcessingException: Error closing message content input stream.
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:162)
        at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.close(WrappedResponseInputStream.java:60)
        at java_io_Closeable$close$0.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.container.DockerCopyFileFromContainer.runRemoteCommand(DockerCopyFileFromContainer.groovy:83)
(...)
Caused by: com.bmuschko.gradle.docker.shaded.org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:254)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:226)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:185)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:214)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:317)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:143)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:94)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$2.close(ApacheConnector.java:659)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:636)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159)
```

(Excuse me that I did not declare `stopSeleniumContainer` as a finalizer in this test, I just wanted to sketch up something quickly. Also, ignore the hard timeout in `stopSeleniumVideo`, it is not necessary, I was just debugging an issue with write permission when binding `/videos` as a mount instead of copying video files...)

### Context
I'm trying to set up a Gradle plugin that configures end-to-end tests to run against a browser running in Docker. For CI builds, I would also want them to record a video of what the browser is doing. Then I want the videos to be accessible e.g. in reports.

### Steps to Reproduce (for bugs)
See attachment.

### Your Environment
RHEL7, Mac 10.12, and Windows 10. I got the same error on all environments.

**Comment by cdancy** [comment]
Ran things locally and was able to get things to pop though each successive run popped for a different reason. Searched around on the internets and looks like this particular issue can pop for various reasons. To try and get to the root of your issue you might want to create a very simple gradle project where all it does is copy things out of some previously started running container using this library and see if things pop then. Might be the image itself is wonky or something else is at play. Can you copy contents out of the container using docker cli?

**Comment by bmuschko** [comment]
Closing as we didn't receive any response.

**Comment by nikshenoy** [comment]
I'm also getting this error when trying to copy a file out of a container. I can copy the file manually from the container using `docker cp`. This error gets thrown on my Windows 10 machine, but works perfectly with the same codebase and build files on MacOS. 
```
 task buildLayerImage(type: DockerBuildImage) {
	inputs.file('layer/requirements.txt')
	dockerFile = file('layer/Dockerfile')
	inputDir = file('layer')
	tags.add('layer/mcm:latest')
 }

 task createLayerContainer(type: DockerCreateContainer) {
	dependsOn buildLayerImage
	imageId = buildLayerImage.imageId
 }

 task copyLayerImage(type: DockerCopyFileFromContainer) {
	dependsOn createLayerContainer
	containerId = createLayerContainer.containerId
	remotePath = '/var/task/layer.zip'
	hostPath = 'deploy'
 }
```
