### ISSUE TITLE
java.io.IOException: Couldn't load native library with Java 11

### ISSUE THREAD

**Issue by jim-chewy** [bmuschko/gradle-docker-plugin#874]
Running `./gradlew clean dockerBuildImage` results in the error mentioned in the subject

### Expected Behavior
Image should be built

### Current Behavior
Using OpenJDK 8, my images build fine
Using OpenJDK 11, I get the error

### Context
I'm not able to build images with OpenJDK 11

### Steps to Reproduce (for bugs)
[ioexception.tar.gz](https://github.com/bmuschko/gradle-docker-plugin/files/3730613/ioexception.tar.gz)
Compile the attached with OpenJDK 11, should get the output shown below Environment section

### Your Environment
`~/IdeaProjects/demo$ ./gradlew -version

------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:         11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Mac OS X 10.14.5 x86_64
`
Also tried with Gradle 5.4.1

builds fine with
`JVM:          1.8.0_222 (AdoptOpenJDK 25.222-b10)`

### Output
`~/IdeaProjects/demo$ ./gradlew clean dockerBuildImage
> Task :clean
> Task :compileJava
> Task :processResources
> Task :classes
> Task :dockerSyncBuildContext
> Task :dockerCreateDockerfile
Error during callback
java.io.IOException: Couldn't load native library
        at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:56)
        at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:48)
        at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:77)
        at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:72)
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:51)
        at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:66)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:119)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.newsclub.net.unix.NativeUnixSocket
        at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:54)
        ... 31 more

> Task :dockerBuildImage FAILED
Building image using context '/Users/jm109344/IdeaProjects/demo/build/docker'.
Using tags 'demo:0.0.1-SNAPSHOT' for image.
`

**Comment by bmuschko** [comment]
Docker Java currently does not support Java 11 or higher as observed by the following issues:

* https://github.com/docker-java/docker-java/issues/1244
* https://github.com/docker-java/docker-java/issues/1245

I am going to add a note to the user guide about Java-compatibility.

**Comment by bmuschko** [comment]
FYI: I just released a version of the plugin, 6.2.0, with the latest Docker Java version as dependency. It should be Java 13-compatible AFAIK. Could you please give it a try?

**Comment by jim-chewy** [comment]
Hello,
 I took a project which used the 6.1.1 plugin and tried to compile it with Java 13, which (as expected) failed. I then modified the plugin to be 6.2.0 and when I build I get error saying it can't find 6.2.0. Do I need to add something else to the file? 

_I just got back from vacation and didn't look at the docs yet as I presumed all I had to do was update the version info...._

`./gradlew clean dockerBuildImage

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jim-chewy/IdeaProjects/orchestration/build.gradle' line: 5

* What went wrong:
Plugin [id: 'com.bmuschko.docker-spring-boot-application', version: '6.2.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.bmuschko.docker-spring-boot-application:com.bmuschko.docker-spring-boot-application.gradle.plugin:6.2.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
`

**Comment by bmuschko** [comment]
@jim-chewy Thanks for letting me know. Something the Gradle team needs to figure out: https://gradle-community.slack.com/archives/CA745PZHN/p1584054905033700. Get it from JCenter in the meantime.

**Comment by bmuschko** [comment]
@jim-chewy They deployed a fix and it's available now.

**Comment by jim-chewy** [comment]
Sorry I took so long to get back to this.

> java -version
> openjdk version "13.0.2" 2020-01-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)


`
...
Successfully built 2a9efe0dd05c
Successfully tagged myserver-docker.jfrog.io/dd/orchestor:2.0.2e3ed31-dev
Created image with ID '2a9efe0dd05c'.

BUILD SUCCESSFUL in 41s
6 actionable tasks: 6 executed
`

So it looks like it is working...

Thanks
Jim
