### ISSUE TITLE
Expose "netty config" on docker-client

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#876]
So we've started running into [THIS](https://github.com/docker-java/docker-java/issues/698) issue here in our build pipeline. A user chimed in on that thread with a supposed solution:
```
DockerCmdExecFactory factory= new NettyDockerCmdExecFactory().withConnectTimeout(100000);
DockerClient docker = DockerClientBuilder.getInstance(<some_config>).withDockerCmdExecFactory(factory).build();
```
Was thinking we could wire up the config to expose letting folks programatically do this. Something like:
```
docker {
    url = 'https://192.168.59.103:2376'
    certPath = new File(System.properties['user.home'], '.boot2docker/certs/boot2docker-vm')
    netty {
        connectTimeout = 100000
    }
}
```
Basically if the `netty` closure is present then use it otherwise it's business as usual.

Thoughts/Opinions?

**Comment by bmuschko** [comment]
With that change you would expose internal implementation details which you don't want to do in a public API. The DSL in this case is the public API. You are basically saying "This plugin is using Netty internally in some sort of form". As a result, there's no easy way to switch to a different underlying implementation e.g. the Spotify library. So overall it's a -1 from me.

Alternatively, you could do the following:
1. Set a higher timeout internally as the default. It will probably work for 99% of the cases.
2. If you wanted to make the timeout configurable, then expose a system property. I'd also use a name that doesn't use Netty e.g. `connect.timeout`.

**Comment by cdancy** [comment]
So I put the timeout option in there as am example but not sure if that's the thing that solves the problem. My hunch is that its just an option being shown and the actual solution is in the impl.

Once we move to spotify, assuming that ever happens, that would completely change everything anyway, and we would have to remove loads of stuff all over the place. From my point of view it would just be yet another breaking change we'd have to bump to a new manor version for which we'd already be doing in this case.

**Comment by cdancy** [comment]
I dont agree on the exposing of internal knobs here as you could argue everything we are doing is exposing an internal something or another. It's just an option for users to take advantage of should they need to for their use-case.

We could do something but simply not expose things or let the user know. Just a bummer as we have a process which is dependent on this potential fix and is currently blocked until we get a solution .

**Comment by orzeh** [comment]
@cdancy I agree with @bmuschko  that configuring low level components, which are implementation related, should be done via env variables or system properties.

**Comment by cdancy** [comment]
Oh we could certainly do that via env-vars within this plugin if that's what you guys are thinking. Something like: GDP_DRIVER=netty?

**Comment by bmuschko** [comment]
> I dont agree on the exposing of internal knobs here as you could argue everything we are doing is exposing an internal something or another.

What I mean here is the underlying implementation of how you communicate with the Docker daemon. Users don't need to know and frankly don't care it works.

> GDP_CONN_DRIVER=netty
> GDP_CONN_TIMEOUT=600000

Wha does `GDP` mean? Why is it important to spell out Netty specifically? The Docker Java 
 Javadocs for `NettyDockerCmdExecFactory ` says that it is "experimental". Wouldn't you rather want to set a timeout for the Jersey implementation?

**Comment by cdancy** [comment]
Going over changes locally could we target env-var, sys-prop, and passed along property (precedence taken in order shown)?
```
gdpInternalConnDriver=netty // project property
gdp.internal.conn.driver=netty // sys-prop
GDP_INTERNAL_CONN_DRIVER=netty // env-var
```
Thoughts one way or another? 

GDP = Gradle Docker Plugin

I suspect this is NOT timeout related as the pop happens fairly early on into a given execution and we've got other tasks which run much longer.

**Comment by bmuschko** [comment]
> Going over changes locally could we target env-var, sys-prop, and passed along property (precedence taken in order shown)?

I'd not expose too many options of configurability. It'll just make things more complicated and hasn't really any benefits. If you wanted environment variables then that's fine.

> I suspect this is NOT timeout related as the pop happens fairly early on into a given execution and we've got other tasks which run much longer.

I am confused. Sounds more like you want to expose new things for debugging purposes. Maybe you can start by just using the Docker Java API in a sample project to identify the actual issue. It's likely that you know what operation is failing and then go from there.

**Comment by cdancy** [comment]
Not for debugging purposes as we've already done that. The pop happens when executing `DockerCopyFileFromContainer` with the below stacktrace. Happens about 2 minutes into the process. Just tried with the fix I suggested and things seem to work. Need to run things through our pipeline to confirm which will take a day or so but the error as it stands is repeateable and with this change it goes away. Take that for what you will :)
```
[2019-10-15T23:06:48.024Z] Caused by: com.bmuschko.gradle.docker.shaded.javax.ws.rs.ProcessingException: Error closing message content input stream.
[2019-10-15T23:06:48.024Z] 	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:162)
[2019-10-15T23:06:48.024Z] 	at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.close(WrappedResponseInputStream.java:60)
[2019-10-15T23:06:48.024Z] 	at java_io_Closeable$close.call(Unknown Source)
[2019-10-15T23:06:48.024Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:82)
[2019-10-15T23:06:48.024Z] 	at com.bmuschko.gradle.docker.tasks.container.DockerCopyFileFromContainer.runRemoteCommand(DockerCopyFileFromContainer.groovy:82)
[2019-10-15T23:06:48.024Z] 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:70)
[2019-10-15T23:06:48.024Z] 	at sun.reflect.GeneratedMethodAccessor821.invoke(Unknown Source)
[2019-10-15T23:06:48.024Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-10-15T23:06:48.024Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
[2019-10-15T23:06:48.024Z] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
[2019-10-15T23:06:48.024Z] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
[2019-10-15T23:06:48.024Z] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
[2019-10-15T23:06:48.024Z] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
[2019-10-15T23:06:48.024Z] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
[2019-10-15T23:06:48.024Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:401)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[2019-10-15T23:06:48.024Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[2019-10-15T23:06:48.025Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:390)
[2019-10-15T23:06:48.025Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:373)
[2019-10-15T23:06:48.025Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:79)
[2019-10-15T23:06:48.025Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:210)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
[2019-10-15T23:06:48.025Z] 	at java.util.Optional.orElseGet(Optional.java:267)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
[2019-10-15T23:06:48.025Z] 	at java.util.Optional.map(Optional.java:215)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
[2019-10-15T23:06:48.025Z] 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
[2019-10-15T23:06:48.026Z] 	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
[2019-10-15T23:06:48.026Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:117)
[2019-10-15T23:06:48.026Z] 	... 132 more
[2019-10-15T23:06:48.026Z] Caused by: com.bmuschko.gradle.docker.shaded.org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:254)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:226)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:185)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:214)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:317)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:143)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
[2019-10-15T23:06:48.026Z] 	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227)
[2019-10-15T23:06:48.026Z] 	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:94)
[2019-10-15T23:06:48.026Z] 	at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
[2019-10-15T23:06:48.026Z] 	at java.io.FilterInputStream.close(FilterInputStream.java:181)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$2.close(ApacheConnector.java:659)
[2019-10-15T23:06:48.026Z] 	at java.io.FilterInputStream.close(FilterInputStream.java:181)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:636)
[2019-10-15T23:06:48.026Z] 	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159)
[2019-10-15T23:06:48.026Z] 	... 194 more
```

**Comment by cdancy** [comment]
Though "experimental" all of our functional tests pass with change so that's something
