### ISSUE TITLE
Unable to push to AWS ECR: HttpHostConnectException on port 80

### ISSUE THREAD

**Issue by tmohme-hypoport** [bmuschko/gradle-docker-plugin#901]
I'm trying to push an image with the plugin to AWS ECR, but can't get it working.
Pushing the image with the plugin to hub.docker.com works flawless.
Pushing the image with `aws ecr get-login ...` & `docker login ...` & `docker push ...` to AWS ECR works.

I've tried the `com.patdouble.awsecr` plugin as well as a dyi solution for getting the AWS credentials.  
I'm pretty sure the credentials I obtain are correct since when I use them with the "manual" command-line approach everything works fine.

To me it seems like the task is trying to use HTTP instead of HTTPS, as it probably should.
Am I missing a switch/option to convince the task to use HTTPS?

### Expected Behavior
Execution of the `DockerPushImage` task should succeed. 

### Current Behavior
Execution of the `DockerPushImage` task fails with a HttpHostConnectionException.

```
Error during callback
com.bmuschko.gradle.docker.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 684320889043.dkr.ecr.eu-central-1.amazonaws.com:80 [684320889043.dkr.ecr.eu-central-1.amazonaws.com/35.158.37.20, 684320889043.dkr.ecr.eu-central-1.amazonaws.com/18.195.114.105, 684320889043.dkr.ecr.eu-central-1.amazonaws.com/18.195.171.255, 684320889043.dkr.ecr.eu-central-1.amazonaws.com/18.195.182.134] failed: Operation timed out (Connection timed out)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 21 more
```

### Context
It is noteworthy that the URL I get from `aws ecr get-login` is a HTTP**S** url ("https://684320889043.dkr.ecr.eu-central-1.amazonaws.com"), but the plugin tries to connect to port 80 (which I have verified with Wireshark) and simply doesn't get a response from the host.
I have confirmed the host's behaviour with `curl`:
* No connection via HTTP / on port 80
* Successful connection via HTTPS
I also have verified that I provide the correct HTTPS url to the task.

Getting the AWS ECR credentials and pushing the image currently looks like this:
```
data class AwsEcrCredentials(val username: String, val password: String, val url: String)
fun getAwsEcrCredentials(): AwsEcrCredentials {
  val dockerLoginCommandTokens = getDockerLoginCommand().dropLast(1).split(" ")
  return AwsEcrCredentials(
      username = dockerLoginCommandTokens[3],
      password = dockerLoginCommandTokens[5],
      url = dockerLoginCommandTokens[6]
  )
}

val dockerPushAppImageToAwsEcr = tasks.register<DockerPushImage>("dockerPushAppImageToAwsEcr") {
  group = "docker"
  description = "push docker app image"
  dependsOn(dockerBuildAppImage)

  url.set("https://$dockerAwsRegistry")
  images.add("$dockerAwsRegistry/$dockerAppImageName:$dockerImageTag")

  doFirst {
    val creds = getAwsEcrCredentials()
    with(registryCredentials) {
      url.set(creds.url)
      username.set(creds.username)
      password.set(creds.password)
    }
  }
}
```

### Your Environment
macOS 10.15.2
openjdk 11.0.5
Gradle 5.6.4
com.bmuschko.docker-remote-api 6.1.1
com.patdouble.awsecr 0.6.0

**Comment by bmuschko** [comment]
Just wondering...why are you reading the credentials during Gradle's execution phase (as indicated by the `doFirst`) and not during the configuration phase? It also seems like you are setting the URL twice. Why?

**Comment by tmohme-hypoport** [comment]
We defer fetching the credentials to the execution phase because during a typical development build we don't need to execute the task. It is mainly used in CI builds. The intention was to avoid problems with missing credentials when we don't need them anyway (because the task won't be executed). I can elaborate on this further if you are interested. 

Setting the url twice was not intended. It most probably is a left-over artifact of all the variations I tried to get the things working.
I would expect the setting it the second time (during execution) with the correct value should simply override what was set during configuration.

**Comment by tmohme-hypoport** [comment]
Just did some more tests:

**Set url during configuration and execution (like above)**
=> No connection on port 80, timeout - as described above

**Set url only during execution**
=> Immediate failure during task execution: "Could not push image: unauthorized: authentication required"

**Set url, username, password during configuration**
=> The task finishes successfully (image gets pushed) although I get a `groovy.json.JsonException` (see below).

Successful task:
```
val dockerPushAppImageToAwsEcr = tasks.register<DockerPushImage>("dockerPushAppImageToAwsEcr") {
  group = "docker"
  description = "push docker app image"
  dependsOn(dockerBuildAppImage)

  images.add("$dockerAwsRegistry/$dockerAppImageName:$dockerImageTag")

  val creds = getAwsEcrCredentials()
  with(registryCredentials) {
    url.set(creds.url)
    username.set(creds.username)
    password.set(creds.password)
  }
}
```

The `groovy.json.JsonException` looks similar to issue #887, although the config file exists:
```
Failure when attempting to lookup auth config (docker repository: 490377836669.dkr.ecr.eu-central-1.amazonaws.com, configFile: /Users/<user>/.docker/config.json. Falling back to docker-java default behaviour
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is 'c' with an int value of 99
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
credentials not found in native keychain
^
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:206)
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:157)
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:46)
        at org.apache.groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:384)
        at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:112)
        at groovy.json.JsonSlurper.parseText(JsonSlurper.java:205)
        at com.bmuschko.gradle.docker.internal.RegistryAuthLocator.runCredentialProvider(RegistryAuthLocator.groovy:253)
```

Should I file a new issue for this one?

**Comment by bmuschko** [comment]
> Should I file a new issue for this one?

Upgrade to the lastest version of the plugin. We put in some fixes in the meantime.

**Comment by tmohme-hypoport** [comment]
Upgraded to the latest version (6.1.3) => No more complaints from groovy/json

Thank you very much for your support!
