### ISSUE TITLE
JDK 13 support 

### ISSUE THREAD

**Issue by sergey-morenets** [bmuschko/gradle-docker-plugin#912]
Hi

Is there any plans to support JDK 13 for com.bmuschko.docker-spring-boot-application plugin?
JDK 12 or earlier is already supported. But we use JDK 13 for our project.

**Comment by orzeh** [comment]
@sergey-morenets  please take a look at #905 and #885

**Comment by bmuschko** [comment]
FYI: I just released a version of the plugin, 6.2.0, with the latest Docker Java version as dependency. It should be Java 13-compatible AFAIK. Could you please give it a try?

**Comment by jonatan-ivanov** [comment]
@bmuschko It seems it does not work (at least to me), my env looks like this:
```
❯ gradlew --version                          

------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (AdoptOpenJDK 13.0.2+8)
OS:           Mac OS X 10.15.3 x86_64
```

I'm using the latest release version:
```
classpath 'com.bmuschko:gradle-docker-plugin:6.3.0'
apply plugin: 'com.bmuschko.docker-spring-boot-application'
```

And I'm getting this:
```
❯ gradlew dockerCreateDockerfile --stacktrace                                                                                                    
> Task :bootBuildInfo
> Task :compileJava
> Task :generateGitProperties UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes
> Task :dockerSyncBuildContext
> Task :dockerCreateDockerfile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerCreateDockerfile'.
> Unsupported class file major version 57

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dockerCreateDockerfile'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 57
        at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
        at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
        at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:273)
        at com.bmuschko.gradle.docker.internal.MainClassFinder.createClassDescriptor(MainClassFinder.groovy:161)
        at com.bmuschko.gradle.docker.internal.MainClassFinder.doWithMainClasses(MainClassFinder.groovy:132)
        at com.bmuschko.gradle.docker.internal.MainClassFinder.findSingleMainClass(MainClassFinder.groovy:27)
        at com.bmuschko.gradle.docker.DockerSpringBootApplicationPlugin.findMainClassName(DockerSpringBootApplicationPlugin.groovy:32)
        at com.bmuschko.gradle.docker.DockerConventionApplicationPlugin.getApplicationMainClassName(DockerConventionApplicationPlugin.groovy:199)
        at com.bmuschko.gradle.docker.DockerConventionApplicationPlugin.access$0(DockerConventionApplicationPlugin.groovy)
        at com.bmuschko.gradle.docker.DockerConventionApplicationPlugin$1$6.call(DockerConventionApplicationPlugin.groovy:125)
        at com.bmuschko.gradle.docker.DockerConventionApplicationPlugin$1$6.call(DockerConventionApplicationPlugin.groovy)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:99)
        at com.bmuschko.gradle.docker.tasks.image.Dockerfile$StringArrayInstruction.getText(Dockerfile.groovy:1028)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:79)
        at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:218)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:75)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.call(AbstractNestedRuntimeBeanNode.java:145)
        at org.gradle.api.internal.tasks.properties.AbstractValidatingProperty.validate(AbstractValidatingProperty.java:39)
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.validate(DefaultTaskProperties.java:193)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.validate(ExecuteActionsTaskExecuter.java:505)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:50)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 23 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
6 actionable tasks: 4 executed, 2 up-to-date
```

It works If I change the JDK to 11.
It also works if my JDK is 13 but I downgrade the target and the source versions to 11:
```
sourceCompatibility = 11
targetCompatibility = 11
```

**Comment by bmuschko** [comment]
@jonatan-ivanov Not quite sure. Your JDK distribution is probably not compatible with the version of Gradle you are using. Try the OpenJDK instead. Or the ASM library defined as transitive dependency of Docker Java clashes with ASM in Gradle in some way.

**Comment by jonatan-ivanov** [comment]
@bmuschko 

>Your JDK distribution is probably not compatible with the version of Gradle you are using.

So are you saying that AdoptOpenJDK (an OpenJDK build) is not compatible with Gradle and that causes this issue? Could you please help me to understand how? o.O

>Try the OpenJDK instead.

I did, I get the same error with these:

```
❯ java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

```
❯ gradlew --version

------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.15.3 x86_64
```

>Or the ASM library defined as transitive dependency of Docker Java clashes with ASM in Gradle in some way.

This makes more sense to me and if you check the last few lines of my previous comment, that's what I'm suspicious at too except I'm not sure it is `docker-java` since [this plugin contains a shaded asm](https://github.com/bmuschko/gradle-docker-plugin/blob/master/build.gradle.kts#L29) too: 

```
shaded("org.ow2.asm:asm:7.0")
``` 
and it seems the exception is coming from there:
```
at com.bmuschko.gradle.docker.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
```
([here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/internal/MainClassFinder.groovy#L161)).

I also ran `./gradlew dependencies` and it seems the only asm lib which resolved is coming from the dependencies of this plugin.
Also, `org.ow2.asm:asm:7.0` seems pretty old ([2018 Oct](https://search.maven.org/artifact/org.ow2.asm/asm)) so there is a good chance that it does not support Java 13.

**Comment by bmuschko** [comment]
RE: My responses - I just added a couple of thoughts without having a deeper look. Didn't really have the bandwidth to think about it. I just had another look and I think your theory is correct that the used ASM version/distro is not fully compatible with the version of Java 13 you are using. It's kind of surprising that you are the only one experiencing the issue. Others using Java 13 confirmed that it works for them.

**Comment by jonatan-ivanov** [comment]
I think the trick that this issue only presents if you are using the `docker-spring-boot-application` plugin and do not set the `mainClassName` so the plugin tries to find it (using asm).
So I guess others might use the other plugins or set the `mainClassName` manually.

**Comment by bmuschko** [comment]
Yeah, that might be the reason.
