### ISSUE TITLE
DockerBuildImage hangs when specifying image name with upper case

### ISSUE THREAD

**Issue by Charleeboyle** [bmuschko/gradle-docker-plugin#915]
When running DockerBuildImage through the docker-remote-api and attempting to specify `images.add('some_name')` where `some_name` includes a upper-case letter, the ./gradlew build hangs.

### Expected Behavior

Docker provides message `invalid argument "some_name" for "-t, --tag" flag: invalid reference format: repository name must be lowercase` when attempting to name image tag with an upper-case letter.

### Current Behavior

Gradle builds indefinitely at `DockerBuildImage` stage, no error is provided.

### Context

Using Gradle to build docker image from Dockerfile to be used for functional testing.

### Steps to Reproduce (for bugs)

code : 
```
buildscript {
  repositories {
    mavenCentral()
  }
}

plugins {
  id 'com.bmuschko.docker-remote-api' version '6.1.3'
}

repositories {
    jcenter()
}

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

// Use task types
task buildImage(type: DockerBuildImage) {
    inputDir = project.projectDir
    images.add('someName')
}

```

Running `./gradlew build`
### Your Environment

* MacOS Catelina
* running `./gradlew build` in VSCode terminal.
* Plugin by DSL `com.bmuschko.docker-remote-api' version '6.1.3'`
* Same issue running plugin using build script syntax

**Comment by orzeh** [comment]
@Charleeboyle I couldn't reproduce the issue with the sample build script you attached on my local Linux box. I needed to remove the `build.dependsOn 'buildImage'` line because it was causing build errors so I assume your build script contains some other tasks/plugins. Can you check it with different OS?

**Comment by Charleeboyle** [comment]
Hi, so I have been following https://bmuschko.github.io/gradle-docker-plugin/#remote_api_plugin

My code does include additional tasks/plugins - Were you able to build a docker image after removing `build.dependsOn 'buildImage'` or do you receive the Docker error `invalid argument "some_name" for "-t, --tag" flag: invalid reference format: repository name must be lowercase` ?

**Comment by orzeh** [comment]
@Charleeboyle sorry I wasn't clear, yes I got the error:
````console
orzeh@dell~/p/gradle_plugin_test> gradle buildImage
Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: invalid reference format: repository name must be lowercase
        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:59)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:133)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:121)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:283)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)

> Task :buildImage FAILED
Building image using context 'gradle_plugin_test'.
Using images 'someName'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> invalid reference format: repository name must be lowercase

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
````

**Comment by bmuschko** [comment]
Sounds like there is no issue?
